Script improvements: * Ensure that Bash 4.4 or higher is used. * Ensure that getopt is enhanced/GNU getopt.

diff --git a/src/X509/extract-pem b/src/X509/extract-pem
--- a/src/X509/extract-pem
+++ b/src/X509/extract-pem
@@ -57,7 +57,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
+   exit 1
+fi
 GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o o:1flqhv --long output-prefix:,only-first-entry,skip-first-entry,skip-last-entry,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -100,7 +108,7 @@ while [ $# -gt 0 ] ; do
          ;;
       *)
          # This should not happen: wrong getopt parameters, or missing case?
-         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
          exit 1
          ;;
   esac
