Minor clean-ups.

diff --git a/src/X509/view-certificate b/src/X509/view-certificate
--- a/src/X509/view-certificate
+++ b/src/X509/view-certificate
@@ -77,15 +77,15 @@ fi
 while [ $# -gt 0 ] ; do
 
    # ====== Look for certificate ============================================
-   CERT="$1"
+   CERTIFICATE_FILE="$1"
    shift
-   if [ ! -e "${CERT}" ] ; then
-      echo >&2 "ERROR: Unable to find certificate file ${CERT}!"
+   if [ ! -e "${CERTIFICATE_FILE}" ] ; then
+      echo >&2 "ERROR: Unable to find certificate file ${CERTIFICATE_FILE}!"
       exit 1
    fi
 
-   echo -e "\e[34mCertificate ${CERT}:\e[0m"
-   "${OPENSSL}" x509 -in "${CERT}" -noout -subject -dates -ext subjectAltName,basicConstraints,keyUsage,extendedKeyUsage,subjectKeyIdentifier,authorityKeyIdentifier | (
+   echo -e "\e[34mCertificate ${CERTIFICATE_FILE}:\e[0m"
+   "${OPENSSL}" x509 -in "${CERTIFICATE_FILE}" -noout -subject -dates -ext subjectAltName,basicConstraints,keyUsage,extendedKeyUsage,subjectKeyIdentifier,authorityKeyIdentifier | (
       validityFrom="?"
       validityTo="?"
       subject="?"
@@ -135,7 +135,7 @@ while [ $# -gt 0 ] ; do
    echo -en "\e[0m"
 
    echo -e "\e[33mHierarchy:\e[0m"
-   "${OPENSSL}" crl2pkcs7 -nocrl -certfile "${CERT}" | \
+   "${OPENSSL}" crl2pkcs7 -nocrl -certfile "${CERTIFICATE_FILE}" | \
       "${OPENSSL}" pkcs7 -print_certs -noout | (
          entry=0
          while read -r line ; do
