Options handling improvements.

diff --git a/src/Try-Hard/try-hard b/src/Try-Hard/try-hard
--- a/src/Try-Hard/try-hard
+++ b/src/Try-Hard/try-hard
@@ -138,6 +138,12 @@ while [ $# -gt 0 ] ; do
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
+         # shift
+         ;;
   esac
 done
 if [ $# -lt 3 ] ; then
