Improved dependency installation hints.

diff --git a/src/Unix-Timestamp/run-tests b/src/Unix-Timestamp/run-tests
--- a/src/Unix-Timestamp/run-tests
+++ b/src/Unix-Timestamp/run-tests
@@ -131,38 +131,38 @@ echo "++++++ Automatic Float, negative ++++++"
 # ====== Find tools =========================================================
 if ! command -v print-utf8 >/dev/null ; then
    echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed! Try:"
-   echo >&2 "* Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
+   echo >&2 " * Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
    echo >&2 "           sudo apt install -y td-system-tools"
-   echo >&2 "* Fedora:  sudo dnf copr enable -y dreibh/ppa"
+   echo >&2 " * Fedora:  sudo dnf copr enable -y dreibh/ppa"
    echo >&2 "           sudo dnf install -y td-system-tools"
-   echo >&2 "* FreeBSD: sudo pkg install -y td-system-tools"
-   echo >&2 "* See https://www.nntb.no/~dreibh/system-tools/#binary-package-installation for other systems!"
+   echo >&2 " * FreeBSD: sudo pkg install -y td-system-tools"
+   echo >&2 " * See https://www.nntb.no/~dreibh/system-tools/#binary-package-installation for other systems!"
    exit 1
 fi
 if ! command -v figlet >/dev/null ; then
-   echo >&2 "ERROR: Figlet is not installed!"
-   echo >&2 "* Ubuntu/Debian: sudo apt install -y figlet"
-   echo >&2 "* Fedora:        sudo dnf install -y figlet"
-   echo >&2 "* OpenSUSE:      sudo zypper install -y figlet"
-   echo >&2 "* Alpine:        sudo apk add figlet"
-   echo >&2 "* FreeBSD:       sudo pkg install -y figlet"
-   echo >&2 "* NetBSD:        sudo pkgin -y install figlet"
-   echo >&2 "* OpenBSD:       sudo pkg_add figlet"
-   echo >&2 "* Solaris:       (install from sources)"
-   echo >&2 "* Apple:         brew install figlet"
+   echo >&2 "ERROR: Figlet is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y figlet"
+   echo >&2 " * Fedora:        sudo dnf install -y figlet"
+   echo >&2 " * OpenSUSE:      sudo zypper install -y figlet"
+   echo >&2 " * Alpine:        sudo apk add figlet"
+   echo >&2 " * FreeBSD:       sudo pkg install -y figlet"
+   echo >&2 " * NetBSD:        sudo pkgin -y install figlet"
+   echo >&2 " * OpenBSD:       sudo pkg_add figlet"
+   echo >&2 " * Solaris:       (install from sources)"
+   echo >&2 " * Apple:         brew install figlet"
    exit 1
 fi
 if ! command -v gawk 2>/dev/null ; then
    echo >&2 "ERROR: GAWK is not installed!"
-   echo >&2 "* Ubuntu/Debian: sudo apt install -y gawk"
-   echo >&2 "* Fedora:        sudo dnf install -y gawk"
-   echo >&2 "* OpenSUSE:      sudo zypper install -y gawk"
-   echo >&2 "* Alpine:        sudo apk add gawk"
-   echo >&2 "* FreeBSD:       sudo pkg install -y gawk"
-   echo >&2 "* NetBSD:        sudo pkgin -y install gawk"
-   echo >&2 "* OpenBSD:       sudo pkg_add gawk"
-   echo >&2 "* Solaris:       sudo pkg install gawk"
-   echo >&2 "* Apple:         brew install gawk"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gawk"
+   echo >&2 " * Fedora:        sudo dnf install -y gawk"
+   echo >&2 " * OpenSUSE:      sudo zypper install -y gawk"
+   echo >&2 " * Alpine:        sudo apk add gawk"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gawk"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gawk"
+   echo >&2 " * OpenBSD:       sudo pkg_add gawk"
+   echo >&2 " * Solaris:       sudo pkg install gawk"
+   echo >&2 " * Apple:         brew install gawk"
    exit 1
 fi
 
