Further improvements for GIMP message filtering in non-verbose mode.

diff --git a/src/GIMP-Scripts/gs-bumpmap b/src/GIMP-Scripts/gs-bumpmap
--- a/src/GIMP-Scripts/gs-bumpmap
+++ b/src/GIMP-Scripts/gs-bumpmap
@@ -446,7 +446,7 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
