Improved options handling.

diff --git a/src/GIMP-Scripts/gs-bumpmap b/src/GIMP-Scripts/gs-bumpmap
--- a/src/GIMP-Scripts/gs-bumpmap
+++ b/src/GIMP-Scripts/gs-bumpmap
@@ -89,166 +89,171 @@ VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
       -C | --compensate-darkening)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         COMPENSATE="$2"
+         shift
+         if [[ "${COMPENSATE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             COMPENSATE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${COMPENSATE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             COMPENSATE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -C|--compensate-darkening!"
+            echo >&2 "ERROR: Invalid value ${COMPENSATE} for -C|--compensate-darkening!"
             exit 1
          fi
-         shift 2
          ;;
       -I | --invert)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
-            TILED="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
-            TILED="FALSE"
+         INVERT="$2"
+         shift
+         if [[ "${INVERT}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+            INVERT="TRUE"
+         elif [[ "${INVERT}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+            INVERT="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -I|--invert!"
+            echo >&2 "ERROR: Invalid value ${INVERT} for -I|--invert!"
             exit 1
          fi
-         shift 2
          ;;
       -T | --tiled)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         TILED="$2"
+         shift
+         if [[ "${TILED}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             TILED="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${TILED}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             TILED="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -T|--tiled!"
+            echo >&2 "ERROR: Invalid value ${TILED} for -T|--tiled!"
             exit 1
          fi
-         shift 2
          ;;
       -A | --azimut)
          AZIMUT="$2"
+         shift
          if [[ ! "${AZIMUT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$ ]] || \
             awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
             exit 1
          fi
-         shift 2
          ;;
       -E | --elevation)
          ELEVATION="$2"
+         shift
          if [[ ! "${ELEVATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
-         shift 2
          ;;
       -D | --depth)
+         DEPTH="$2"
+         shift
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
             echo >&2 "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
-         shift 2
          ;;
       -X | --offset-x)
          OFFSET_X="$2"
+         shift
          if [[ ! "${OFFSET_X}" =~ ^[0-9]+$ ]] || [ "${OFFSET_X}" -lt -20000 ] || [ "${OFFSET_X}" -gt 20000 ] ; then
             echo >&2 "ERROR: Invalid value ${OFFSET_X} for -X|--offset-x!"
             exit 1
          fi
-         shift 2
          ;;
       -Y | --offset-y)
          OFFSET_Y="$2"
+         shift
          if [[ ! "${OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${OFFSET_Y}" -lt -20000 ] || [ "${OFFSET_Y}" -gt 20000 ] ; then
             echo >&2 "ERROR: Invalid value ${OFFSET_Y} for -Y|--offset-y!"
             exit 1
          fi
-         shift 2
          ;;
       -W | --waterlevel)
          WATERLEVEL="$2"
+         shift
          if [[ ! "${WATERLEVEL}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($WATERLEVEL < 0.0) || ($WATERLEVEL > 1.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${WATERLEVEL} for -W|--waterlevel!"
             exit 1
          fi
-         shift 2
          ;;
       -B | --ambient)
          AMBIENT="$2"
+         shift
          if [[ ! "${AMBIENT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($AMBIENT < 0.0) || ($AMBIENT > 1.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${AMBIENT} for -B|--ambient!"
             exit 1
          fi
-         shift 2
          ;;
 
       -H | --hue-range)
-         if [[ ! -v hueRanges["$2"] ]] ; then
-            echo >&2 "ERROR: Invalid value $2 for -H|--hue-range!"
+         HUE_RANGE="$2"
+         shift
+         if [[ ! -v hueRanges["${HUE_RANGE}"] ]] ; then
+            echo >&2 "ERROR: Invalid value ${HUE_RANGE} for -H|--hue-range!"
             exit 1
          fi
          HUE_RANGE="${hueRanges[$2]}"
-         shift 2
          ;;
       -O | --hue-offset)
          HUE_OFFSET="$2"
+         shift
          if [[ ! "${HUE_OFFSET}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($HUE_OFFSET < -180.0) || ($HUE_OFFSET > 180.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${HUE_OFFSET} for -O|--hue-offset!"
             exit 1
          fi
-         shift 2
          ;;
       -L | --lightness)
          LIGHTNESS="$2"
+         shift
          if [[ ! "${LIGHTNESS}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($LIGHTNESS < -100.0) || ($LIGHTNESS > 100.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${LIGHTNESS} for -L|--lightness!"
             exit 1
          fi
-         shift 2
          ;;
       -S | --saturation)
          SATURATION="$2"
+         shift
          if [[ ! "${SATURATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($SATURATION < -100.0) || ($SATURATION > 100.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${SATURATION} for -S|--saturation!"
             exit 1
          fi
-         shift 2
          ;;
       -V | --overlap)
          OVERLAP="$2"
+         shift
          if [[ ! "${OVERLAP}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($OVERLAP < 0.0) || ($OVERLAP > 100.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${OVERLAP} for -V|--overlap!"
             exit 1
          fi
-         shift 2
          ;;
 
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
diff --git a/src/GIMP-Scripts/gs-caption b/src/GIMP-Scripts/gs-caption
--- a/src/GIMP-Scripts/gs-caption
+++ b/src/GIMP-Scripts/gs-caption
@@ -70,64 +70,63 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -F | --font-name)
          FONT_NAME="$2"
-         shift 2
+         shift
          ;;
       -S | --font-size)
          FONT_SIZE="$2"
+         shift
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
             exit 1
          fi
-         shift 2
          ;;
       -f | --foreground)
          COLOR_FOREGROUND="$2"
+         shift
          if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
             echo >&2 "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
             exit 1
          fi
-         shift 2
          ;;
       -b | --background)
          COLOR_BACKGROUND="$2"
+         shift
          if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
             echo >&2 "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
             exit 1
          fi
-         shift 2
          ;;
       -t | --transparency)
          TRANSPARENCY="$2"
+         shift
          if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
             echo >&2 "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
             exit 1
          fi
-         TRANSPARENCY="$2"
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 4 ] ; then
diff --git a/src/GIMP-Scripts/gs-clothify b/src/GIMP-Scripts/gs-clothify
--- a/src/GIMP-Scripts/gs-clothify
+++ b/src/GIMP-Scripts/gs-clothify
@@ -70,68 +70,69 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -X | --blur-x)
          BLUR_X="$2"
+         shift
          if [[ ! "${BLUR_X}" =~ ^[0-9]+$ ]] || [ "${BLUR_X}" -lt 3 ] || [ "${BLUR_X}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${BLUR_X} for -X|--blur-x!"
             exit 1
          fi
-         shift 2
          ;;
       -Y | --blur-y)
          BLUR_Y="$2"
+         shift
          if [[ ! "${BLUR_Y}" =~ ^[0-9]+$ ]] || [ "${BLUR_Y}" -lt 3 ] || [ "${BLUR_Y}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${BLUR_Y} for -Y|--blur-y!"
             exit 1
          fi
-         shift 2
          ;;
       -A | --azimut)
          AZIMUT="$2"
+         shift
          if [[ ! "${AZIMUT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
             exit 1
          fi
-         shift 2
          ;;
       -E | --elevation)
          ELEVATION="$2"
+         shift
          if [[ ! "${ELEVATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
-         shift 2
          ;;
       -D | --depth)
+         DEPTH="$2"
+         shift
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
             echo >&2 "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
diff --git a/src/GIMP-Scripts/gs-glossytext b/src/GIMP-Scripts/gs-glossytext
--- a/src/GIMP-Scripts/gs-glossytext
+++ b/src/GIMP-Scripts/gs-glossytext
@@ -82,157 +82,163 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -F | --font-name)
          FONT_NAME="$2"
-         shift 2
+         shift
          ;;
       -S | --font-size)
          FONT_SIZE="$2"
+         shift
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] ; then
             echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -S|--font-size!"
             exit 1
          fi
-         shift 2
          ;;
 
       -G | --blend-gradient-text)
          BLEND_GRADIENT_TEXT="$2"
-         shift 2
+         shift
          ;;
       -g | --blend-gradient-text-reverse)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         BLEND_GRADIENT_TEXT_REVERSE="$2"
+         shift
+         if [[ "${BLEND_GRADIENT_TEXT_REVERSE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             BLEND_GRADIENT_TEXT_REVERSE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${BLEND_GRADIENT_TEXT_REVERSE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             BLEND_GRADIENT_TEXT_REVERSE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -g|--blend-gradient-text-reverse!"
+            echo >&2 "ERROR: Invalid value ${BLEND_GRADIENT_TEXT_REVERSE} for -g|--blend-gradient-text-reverse!"
             exit 1
          fi
-         shift 2
          ;;
       -L | --blend-gradient-outline)
          BLEND_GRADIENT_OUTLINE="$2"
-         shift 2
+         shift
          ;;
       -l | --blend-gradient-outline-reverse)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         BLEND_GRADIENT_OUTLINE_REVERSE="$2"
+         shift
+         if [[ "${BLEND_GRADIENT_OUTLINE_REVERSE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             BLEND_GRADIENT_OUTLINE_REVERSE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${BLEND_GRADIENT_OUTLINE_REVERSE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             BLEND_GRADIENT_OUTLINE_REVERSE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -l|--blend-gradient-outline-reverse!"
+            echo >&2 "ERROR: Invalid value ${BLEND_GRADIENT_OUTLINE_REVERSE} for -l|--blend-gradient-outline-reverse!"
             exit 1
          fi
-         shift 2
          ;;
       -O | --outline-size)
          OUTLINE_SIZE="$2"
+         shift
          if [[ ! "${OUTLINE_SIZE}" =~ ^[0-9]+$ ]] || [ "${OUTLINE_SIZE}" -lt 2 ] || [ "${OUTLINE_SIZE}" -gt 250 ] ; then
             echo >&2 "ERROR: Invalid value ${OUTLINE_SIZE} for -O|--outline-size!"
             exit 1
          fi
-         shift 2
          ;;
       -B | --background-color)
          BACKGROUND_COLOR="$2"
-         shift 2
+         shift
          ;;
 
       -I | --pattern-text)
          PATTERN_TEXT="$2"
-         shift 2
+         shift
          ;;
       -i | --use-pattern-text)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_PATTERN_TEXT="$2"
+         shift
+         if [[ "${USE_PATTERN_TEXT}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_PATTERN_TEXT="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_PATTERN_TEXT}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_TEXT="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -i|--use-pattern-text!"
+            echo >&2 "ERROR: Invalid value ${USE_PATTERN_TEXT} for -i|--use-pattern-text!"
             exit 1
          fi
-         shift 2
          ;;
       -J | --pattern-outline)
          PATTERN_OUTLINE="$2"
-         shift 2
+         shift
          ;;
       -j | --use-pattern-outline)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_PATTERN_OUTLINE="$2"
+         shift
+         if [[ "${USE_PATTERN_OUTLINE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_PATTERN_OUTLINE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_PATTERN_OUTLINE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_OUTLINE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -j|--use-pattern-outline!"
+            echo >&2 "ERROR: Invalid value ${USE_PATTERN_OUTLINE} for -j|--use-pattern-outline!"
             exit 1
          fi
-         shift 2
          ;;
       -R | --pattern-overlay)
          PATTERN_OVERLAY="$2"
-         shift 2
+         shift
          ;;
       -r | --use-pattern-overlay)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_PATTERN_OVERLAY="$2"
+         shift
+         if [[ "${USE_PATTERN_OVERLAY}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_PATTERN_OVERLAY="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_PATTERN_OVERLAY}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_OVERLAY="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -r|--use-pattern-overlay!"
+            echo >&2 "ERROR: Invalid value ${USE_PATTERN_OVERLAY} for -r|--use-pattern-overlay!"
             exit 1
          fi
-         shift 2
          ;;
 
       -s | --use-shadow)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_SHADOW="$2"
+         shift
+         if [[ "${USE_SHADOW}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_SHADOW="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_SHADOW}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_SHADOW="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -s|--use-shadow!"
+            echo >&2 "ERROR: Invalid value ${USE_SHADOW} for -s|--use-shadow!"
             exit 1
          fi
-         shift 2
          ;;
       -X | --shadow-offset-x)
          SHADOW_OFFSET_X="$2"
+         shift
          if [[ ! "${SHADOW_OFFSET_X}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_X}" -lt 1 ] || [ "${SHADOW_OFFSET_X}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_X} for -X|--shadow-offset-x!"
             exit 1
          fi
-         shift 2
          ;;
       -Y | --shadow-offet-y)
          SHADOW_OFFSET_Y="$2"
+         shift
          if [[ ! "${SHADOW_OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_Y}" -lt 1 ] || [ "${SHADOW_OFFSET_Y}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offet-y!"
             exit 1
          fi
-         shift 2
          ;;
 
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
diff --git a/src/GIMP-Scripts/gs-oilify b/src/GIMP-Scripts/gs-oilify
--- a/src/GIMP-Scripts/gs-oilify
+++ b/src/GIMP-Scripts/gs-oilify
@@ -67,46 +67,47 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -S | --mask-size)
          MASK_SIZE="$2"
+         shift
          if [[ ! "${MASK_SIZE}" =~ ^([0-9]+)$ ]] ; then
             echo >&2 "ERROR: Invalid value ${MASK_SIZE} for -S|--mask-size!"
             exit 1
          fi
-         shift 2
          ;;
       -I | --intensity-mode)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         INTENSITY_MODE="$2"
+         shift
+         if [[ "${INTENSITY_MODE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             INTENSITY_MODE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${INTENSITY_MODE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             INTENSITY_MODE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -I|--intensity-mode!"
+            echo >&2 "ERROR: Invalid value ${INTENSITY_MODE} for -I|--intensity-mode!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
diff --git a/src/GIMP-Scripts/gs-oldphoto b/src/GIMP-Scripts/gs-oldphoto
--- a/src/GIMP-Scripts/gs-oldphoto
+++ b/src/GIMP-Scripts/gs-oldphoto
@@ -68,69 +68,72 @@ VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
       -D | --defocus)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         DEFOCUS="$2"
+         shift
+         if [[ "${DEFOCUS}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             DEFOCUS="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${DEFOCUS}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             DEFOCUS="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -D|--defocus!"
+            echo >&2 "ERROR: Invalid value ${DEFOCUS} for -D|--defocus!"
             exit 1
          fi
-         shift 2
          ;;
       -B | --border-size)
          BORDER_SIZE="$2"
+         shift
          if [[ ! "${BORDER_SIZE}" =~ ^[0-9]+$ ]] ; then
             echo >&2 "ERROR: Invalid value ${BORDER_SIZE} for -B|--border-size!"
             exit 1
          fi
-         shift 2
          ;;
       -S | --sepia)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         SEPIA="$2"
+         shift
+         if [[ "${SEPIA}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             SEPIA="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${SEPIA}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             SEPIA="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -S|--sepia!"
+            echo >&2 "ERROR: Invalid value ${SEPIA} for -S|--sepia!"
             exit 1
          fi
-         shift 2
          ;;
       -M | --mottle)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         MOTTLE="$2"
+         shift
+         if [[ "${MOTTLE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             MOTTLE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${MOTTLE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             MOTTLE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -M|--mottle!"
+            echo >&2 "ERROR: Invalid value ${MOTTLE} for -M|--mottle!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
diff --git a/src/GIMP-Scripts/gs-resize-with-cropping b/src/GIMP-Scripts/gs-resize-with-cropping
--- a/src/GIMP-Scripts/gs-resize-with-cropping
+++ b/src/GIMP-Scripts/gs-resize-with-cropping
@@ -68,27 +68,24 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -A | --aspect)
          ASPECT="$2"
-         shift 2
+         shift
          ;;
       -W | --width)
          NEW_WIDTH="$2"
-         shift 2
+         shift
          ;;
       -H | --height)
          NEW_HEIGHT="$2"
-         shift 2
+         shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
@@ -98,9 +95,12 @@ while [ $# -gt 0 ] ; do
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
diff --git a/src/GIMP-Scripts/gs-test-gimp b/src/GIMP-Scripts/gs-test-gimp
--- a/src/GIMP-Scripts/gs-test-gimp
+++ b/src/GIMP-Scripts/gs-test-gimp
@@ -66,27 +66,27 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 0 ] ; then
