Further improvements and clean-ups.

diff --git a/src/GIMP-Scripts/gs-glossytext b/src/GIMP-Scripts/gs-glossytext
--- a/src/GIMP-Scripts/gs-glossytext
+++ b/src/GIMP-Scripts/gs-glossytext
@@ -35,7 +35,7 @@ set -euo pipefail
 # ###### Usage ##############################################################
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 filename text [-F|--font-name font] [-S|--font-size size] [-G|--blend-gradient-text gradient] [-g|--blend-gradient-text-reverse on|off] [-L|--blend-gradient-outline gradient] [-l|--blend-gradient-outline-reverse on|off] [-O|--outline-size size] [-B|--background-color color] [-I|--pattern-text pattern] [-i|--use-pattern-text on|off] [-J|--pattern-outline pattern] [-j|--use-pattern-outline on|off] [-R|--pattern-overlay pattern] [-r|--use-pattern-overlay on|off] [-s|--use-shadow on|off] [-X|--shadow-offset-x offset] [-Y|--shadow-offset-y offset] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
+   echo >&2 "Usage: $0 output_filename text [-F|--font-name font] [-S|--font-size size] [-G|--blend-gradient-text gradient] [-g|--blend-gradient-text-reverse on|off] [-L|--blend-gradient-outline gradient] [-l|--blend-gradient-outline-reverse on|off] [-O|--outline-size size] [-B|--background-color color] [-I|--pattern-text pattern] [-i|--use-pattern-text on|off] [-J|--pattern-outline pattern] [-j|--use-pattern-outline on|off] [-R|--pattern-overlay pattern] [-r|--use-pattern-overlay on|off] [-s|--use-shadow on|off] [-X|--shadow-offset-x offset] [-Y|--shadow-offset-y offset] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
    exit "${exitCode}"
 }
 
@@ -214,11 +214,11 @@ while [ $# -gt 0 ] ; do
             exit 1
          fi
          ;;
-      -Y | --shadow-offet-y)
+      -Y | --shadow-offset-y)
          SHADOW_OFFSET_Y="$2"
          shift
          if [[ ! "${SHADOW_OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_Y}" -lt 1 ] || [ "${SHADOW_OFFSET_Y}" -gt 100 ] ; then
-            echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offet-y!"
+            echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offset-y!"
             exit 1
          fi
          ;;
diff --git a/src/GIMP-Scripts/gs-mosaic b/src/GIMP-Scripts/gs-mosaic
--- a/src/GIMP-Scripts/gs-mosaic
+++ b/src/GIMP-Scripts/gs-mosaic
@@ -175,7 +175,7 @@ while [ $# -gt 0 ] ; do
          elif [[ "${COLOR_AVERAGING}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             COLOR_AVERAGING="FALSE"
          else
-            echo >&2 "ERROR: Invalid value ${COLOR_AVERAGING} for -g|--color-averaging!"
+            echo >&2 "ERROR: Invalid value ${COLOR_AVERAGING} for -G|--color-averaging!"
             exit 1
          fi
          ;;
@@ -196,7 +196,7 @@ while [ $# -gt 0 ] ; do
          shift
          if [[ ! "${LIGHT_DIRECTION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($LIGHT_DIRECTION < 0.0) || ($LIGHT_DIRECTION > 360.0) ? 0 : 1) }" ; then
-            echo >&2 "ERROR: Invalid value ${LIGHT_DIRECTION} for -C|--light-direction!"
+            echo >&2 "ERROR: Invalid value ${LIGHT_DIRECTION} for -L|--light-direction!"
             exit 1
          fi
          ;;
