Updated error messages for consistency with the other tools.

diff --git a/src/GIMP-Scripts/gs-oilify b/src/GIMP-Scripts/gs-oilify
--- a/src/GIMP-Scripts/gs-oilify
+++ b/src/GIMP-Scripts/gs-oilify
@@ -103,7 +103,7 @@ while [ $# -gt 0 ] ; do
          ;;
       *)
          # This should not happen: wrong getopt parameters, or missing case?
-         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
          exit 1
          ;;
   esac
