Improved error handling.

diff --git a/src/GIMP-Scripts/Make-BumpMap b/src/GIMP-Scripts/Make-BumpMap
--- a/src/GIMP-Scripts/Make-BumpMap
+++ b/src/GIMP-Scripts/Make-BumpMap
@@ -80,7 +80,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             COMPENSATE="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -C|--compensate-darkening!"
+            echo >&2 "ERROR: Invalid value $2 for -C|--compensate-darkening!"
+            exit 1
          fi
          shift 2
          ;;
@@ -90,7 +91,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             TILED="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -I|--invert!"
+            echo >&2 "ERROR: Invalid value $2 for -I|--invert!"
+            exit 1
          fi
          shift 2
          ;;
@@ -100,7 +102,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             TILED="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -T|--tiled!"
+            echo >&2 "ERROR: Invalid value $2 for -T|--tiled!"
+            exit 1
          fi
          shift 2
          ;;
@@ -108,7 +111,7 @@ while [ $# -gt 0 ] ; do
          AZIMUT="$2"
          if [[ ! "${AZIMUT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$ ]] || \
             awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
+            echo >&2 "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
             exit 1
          fi
          shift 2
@@ -117,14 +120,14 @@ while [ $# -gt 0 ] ; do
          ELEVATION="$2"
          if [[ ! "${ELEVATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
+            echo >&2 "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
          shift 2
          ;;
       -D | --depth)
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
-            echo "ERROR: Invalid value ${DEPTH} for -D|--depth!"
+            echo >&2 "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
          shift 2
@@ -132,7 +135,7 @@ while [ $# -gt 0 ] ; do
       -X | --offset-x)
          OFFSET_X="$2"
          if [[ ! "${OFFSET_X}" =~ ^[0-9]+$ ]] || [ "${OFFSET_X}" -lt -20000 ] || [ "${OFFSET_X}" -gt 20000 ] ; then
-            echo "ERROR: Invalid value ${OFFSET_X} for -X|--offset-x!"
+            echo >&2 "ERROR: Invalid value ${OFFSET_X} for -X|--offset-x!"
             exit 1
          fi
          shift 2
@@ -140,8 +143,8 @@ while [ $# -gt 0 ] ; do
       -Y | --offset-y)
          OFFSET_Y="$2"
          if [[ ! "${OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${OFFSET_Y}" -lt -20000 ] || [ "${OFFSET_Y}" -gt 20000 ] ; then
-            echo "ERROR: Invalid value ${OFFSET_Y} for -Y|--offset-y!"
-            eyit 1
+            echo >&2 "ERROR: Invalid value ${OFFSET_Y} for -Y|--offset-y!"
+            exit 1
          fi
          shift 2
          ;;
@@ -149,7 +152,7 @@ while [ $# -gt 0 ] ; do
          WATERLEVEL="$2"
          if [[ ! "${WATERLEVEL}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($WATERLEVEL < 0.0) || ($WATERLEVEL > 1.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${WATERLEVEL} for -W|--waterlevel!"
+            echo >&2 "ERROR: Invalid value ${WATERLEVEL} for -W|--waterlevel!"
             exit 1
          fi
          shift 2
@@ -158,7 +161,7 @@ while [ $# -gt 0 ] ; do
          AMBIENT="$2"
          if [[ ! "${AMBIENT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($AMBIENT < 0.0) || ($AMBIENT > 1.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${AMBIENT} for -B|--ambient!"
+            echo >&2 "ERROR: Invalid value ${AMBIENT} for -B|--ambient!"
             exit 1
          fi
          shift 2
@@ -166,7 +169,7 @@ while [ $# -gt 0 ] ; do
 
       -H | --hue-range)
          if [[ ! -v hueRanges["$2"] ]] ; then
-            echo "ERROR: Invalid value $2 for -H|--hue-range!"
+            echo >&2 "ERROR: Invalid value $2 for -H|--hue-range!"
             exit 1
          fi
          HUE_RANGE="${hueRanges[$2]}"
@@ -176,7 +179,7 @@ while [ $# -gt 0 ] ; do
          HUE_OFFSET="$2"
          if [[ ! "${HUE_OFFSET}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($HUE_OFFSET < -180.0) || ($HUE_OFFSET > 180.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${HUE_OFFSET} for -O|--hue-offset!"
+            echo >&2 "ERROR: Invalid value ${HUE_OFFSET} for -O|--hue-offset!"
             exit 1
          fi
          shift 2
@@ -185,7 +188,7 @@ while [ $# -gt 0 ] ; do
          LIGHTNESS="$2"
          if [[ ! "${LIGHTNESS}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($LIGHTNESS < -100.0) || ($LIGHTNESS > 100.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${LIGHTNESS} for -L|--lightness!"
+            echo >&2 "ERROR: Invalid value ${LIGHTNESS} for -L|--lightness!"
             exit 1
          fi
          shift 2
@@ -194,7 +197,7 @@ while [ $# -gt 0 ] ; do
          SATURATION="$2"
          if [[ ! "${SATURATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($SATURATION < -100.0) || ($SATURATION > 100.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${SATURATION} for -S|--saturation!"
+            echo >&2 "ERROR: Invalid value ${SATURATION} for -S|--saturation!"
             exit 1
          fi
          shift 2
@@ -203,7 +206,7 @@ while [ $# -gt 0 ] ; do
          OVERLAP="$2"
          if [[ ! "${OVERLAP}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($OVERLAP < 0.0) || ($OVERLAP > 100.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${OVERLAP} for -V|--overlap!"
+            echo >&2 "ERROR: Invalid value ${OVERLAP} for -V|--overlap!"
             exit 1
          fi
          shift 2
diff --git a/src/GIMP-Scripts/Make-Caption b/src/GIMP-Scripts/Make-Caption
--- a/src/GIMP-Scripts/Make-Caption
+++ b/src/GIMP-Scripts/Make-Caption
@@ -61,7 +61,7 @@ while [ $# -gt 0 ] ; do
       -S | --font-size)
          FONT_SIZE="$2"
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
+            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
             exit 1
          fi
          shift 2
@@ -69,7 +69,7 @@ while [ $# -gt 0 ] ; do
       -f | --foreground)
          COLOR_FOREGROUND="$2"
          if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
-            echo "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
+            echo >&2 "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
             exit 1
          fi
          shift 2
@@ -77,7 +77,7 @@ while [ $# -gt 0 ] ; do
       -b | --background)
          COLOR_BACKGROUND="$2"
          if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
-            echo "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
+            echo >&2 "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
             exit 1
          fi
          shift 2
@@ -85,8 +85,8 @@ while [ $# -gt 0 ] ; do
       -t | --transparency)
          TRANSPARENCY="$2"
          if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
-            echo "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
-            eyit 1
+            echo >&2 "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
+            exit 1
          fi
          TRANSPARENCY="$2"
          shift 2
diff --git a/src/GIMP-Scripts/Make-Clothify b/src/GIMP-Scripts/Make-Clothify
--- a/src/GIMP-Scripts/Make-Clothify
+++ b/src/GIMP-Scripts/Make-Clothify
@@ -57,7 +57,7 @@ while [ $# -gt 0 ] ; do
       -X | --blur-x)
          BLUR_X="$2"
          if [[ ! "${BLUR_X}" =~ ^[0-9]+$ ]] || [ "${BLUR_X}" -lt 3 ] || [ "${BLUR_X}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${BLUR_X} for -X|--blur-x!"
+            echo >&2 "ERROR: Invalid value ${BLUR_X} for -X|--blur-x!"
             exit 1
          fi
          shift 2
@@ -65,8 +65,8 @@ while [ $# -gt 0 ] ; do
       -Y | --blur-y)
          BLUR_Y="$2"
          if [[ ! "${BLUR_Y}" =~ ^[0-9]+$ ]] || [ "${BLUR_Y}" -lt 3 ] || [ "${BLUR_Y}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${BLUR_Y} for -Y|--blur-y!"
-            eyit 1
+            echo >&2 "ERROR: Invalid value ${BLUR_Y} for -Y|--blur-y!"
+            exit 1
          fi
          shift 2
          ;;
@@ -74,7 +74,7 @@ while [ $# -gt 0 ] ; do
          AZIMUT="$2"
          if [[ ! "${AZIMUT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
+            echo >&2 "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
             exit 1
          fi
          shift 2
@@ -83,14 +83,14 @@ while [ $# -gt 0 ] ; do
          ELEVATION="$2"
          if [[ ! "${ELEVATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
+            echo >&2 "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
          shift 2
          ;;
       -D | --depth)
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
-            echo "ERROR: Invalid value ${DEPTH} for -D|--depth!"
+            echo >&2 "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
          shift 2
diff --git a/src/GIMP-Scripts/Make-GlossyText b/src/GIMP-Scripts/Make-GlossyText
--- a/src/GIMP-Scripts/Make-GlossyText
+++ b/src/GIMP-Scripts/Make-GlossyText
@@ -79,7 +79,7 @@ while [ $# -gt 0 ] ; do
       -S | --font-size)
          FONT_SIZE="$2"
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] ; then
-            echo "ERROR: Invalid value ${FONT_SIZE} for -S|--font-size!"
+            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -S|--font-size!"
             exit 1
          fi
          shift 2
@@ -95,7 +95,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             BLEND_GRADIENT_TEXT_REVERSE="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -g|--blend-gradient-text-reverse!"
+            echo >&2 "ERROR: Invalid value $2 for -g|--blend-gradient-text-reverse!"
+            exit 1
          fi
          shift 2
          ;;
@@ -109,15 +110,16 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             BLEND_GRADIENT_OUTLINE_REVERSE="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -l|--blend-gradient-outline-reverse!"
+            echo >&2 "ERROR: Invalid value $2 for -l|--blend-gradient-outline-reverse!"
+            exit 1
          fi
          shift 2
          ;;
       -O | --outline-size)
          OUTLINE_SIZE="$2"
          if [[ ! "${OUTLINE_SIZE}" =~ ^[0-9]+$ ]] || [ "${OUTLINE_SIZE}" -lt 2 ] || [ "${OUTLINE_SIZE}" -gt 250 ] ; then
-            echo "ERROR: Invalid value ${OUTLINE_SIZE} for -O|--outline-size!"
-            eyit 1
+            echo >&2 "ERROR: Invalid value ${OUTLINE_SIZE} for -O|--outline-size!"
+            exit 1
          fi
          shift 2
          ;;
@@ -136,7 +138,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_TEXT="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -i|--use-pattern-text!"
+            echo >&2 "ERROR: Invalid value $2 for -i|--use-pattern-text!"
+            exit 1
          fi
          shift 2
          ;;
@@ -150,7 +153,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_OUTLINE="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -j|--use-pattern-outline!"
+            echo >&2 "ERROR: Invalid value $2 for -j|--use-pattern-outline!"
+            exit 1
          fi
          shift 2
          ;;
@@ -164,7 +168,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_OVERLAY="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -r|--use-pattern-overlay!"
+            echo >&2 "ERROR: Invalid value $2 for -r|--use-pattern-overlay!"
+            exit 1
          fi
          shift 2
          ;;
@@ -175,14 +180,15 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_SHADOW="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -s|--use-shadow!"
+            echo >&2 "ERROR: Invalid value $2 for -s|--use-shadow!"
+            exit 1
          fi
          shift 2
          ;;
       -X | --shadow-offset-x)
          SHADOW_OFFSET_X="$2"
          if [[ ! "${SHADOW_OFFSET_X}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_X}" -lt 1 ] || [ "${SHADOW_OFFSET_X}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${SHADOW_OFFSET_X} for -X|--shadow-offset-x!"
+            echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_X} for -X|--shadow-offset-x!"
             exit 1
          fi
          shift 2
@@ -190,7 +196,7 @@ while [ $# -gt 0 ] ; do
       -Y | --shadow-offet-y)
          SHADOW_OFFSET_Y="$2"
          if [[ ! "${SHADOW_OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_Y}" -lt 1 ] || [ "${SHADOW_OFFSET_Y}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offet-y!"
+            echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offet-y!"
             exit 1
          fi
          shift 2
diff --git a/src/GIMP-Scripts/Make-Mosaic b/src/GIMP-Scripts/Make-Mosaic
--- a/src/GIMP-Scripts/Make-Mosaic
+++ b/src/GIMP-Scripts/Make-Mosaic
@@ -73,7 +73,7 @@ while [ $# -gt 0 ] ; do
          elif [ "${TILE_TYPESTRING}" = "triangles" ] ; then
             TILE_TYPE=3
          else
-            echo "ERROR: Invalid value ${TILE_TYPESTRING} for -T|--tile-type!"
+            echo >&2 "ERROR: Invalid value ${TILE_TYPESTRING} for -T|--tile-type!"
             exit 1
          fi
          shift 2
@@ -82,7 +82,7 @@ while [ $# -gt 0 ] ; do
          TILE_SIZE="$2"
          if [[ ! "${TILE_SIZE}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_SIZE < 1.0) || ($TILE_SIZE > 1000.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${TILE_SIZE} for -S|--tile-size!"
+            echo >&2 "ERROR: Invalid value ${TILE_SIZE} for -S|--tile-size!"
             exit 1
          fi
          shift 2
@@ -91,7 +91,7 @@ while [ $# -gt 0 ] ; do
          TILE_HEIGHT="$2"
          if [[ ! "${TILE_HEIGHT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_HEIGHT < 1.0) || ($TILE_HEIGHT > 1000.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${TILE_HEIGHT} for -H|--tile-height!"
+            echo >&2 "ERROR: Invalid value ${TILE_HEIGHT} for -H|--tile-height!"
             exit 1
          fi
          shift 2
@@ -100,7 +100,7 @@ while [ $# -gt 0 ] ; do
          TILE_NEATNESS="$2"
          if [[ ! "${TILE_NEATNESS}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_NEATNESS < 0.0) || ($TILE_NEATNESS > 1.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${TILE_NEATNESS} for -N|--tile-neatness!"
+            echo >&2 "ERROR: Invalid value ${TILE_NEATNESS} for -N|--tile-neatness!"
             exit 1
          fi
          shift 2
@@ -111,7 +111,7 @@ while [ $# -gt 0 ] ; do
          elif [ "$2" == "rough" ] ; then
             TILE_SURFACE="TRUE"
          else
-            echo "ERROR: Invalid value ${TILE_SURFACE} for -F|--tile-surface!"
+            echo >&2 "ERROR: Invalid value ${TILE_SURFACE} for -F|--tile-surface!"
             exit 1
          fi
          shift 2
@@ -122,7 +122,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             TILE_ALLOW_SPLIT="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -I|--tile-allow-split!"
+            echo >&2 "ERROR: Invalid value $2 for -I|--tile-allow-split!"
+            exit 1
          fi
          shift 2
          ;;
@@ -130,7 +131,7 @@ while [ $# -gt 0 ] ; do
          TILE_SPACING="$2"
          if [[ ! "${TILE_SPACING}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_SPACING < 0.0) || ($TILE_SPACING > 1000.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${TILE_SPACING} for -X|--tile-spacing!"
+            echo >&2 "ERROR: Invalid value ${TILE_SPACING} for -X|--tile-spacing!"
             exit 1
          fi
          shift 2
@@ -139,7 +140,7 @@ while [ $# -gt 0 ] ; do
          COLOR_VARIATION="$2"
          if [[ ! "${COLOR_VARIATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($COLOR_VARIATION < 0.0) || ($COLOR_VARIATION > 1.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${COLOR_VARIATION} for -C|--color-variation!"
+            echo >&2 "ERROR: Invalid value ${COLOR_VARIATION} for -C|--color-variation!"
             exit 1
          fi
          shift 2
@@ -150,7 +151,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             COLOR_AVERAGING="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -g|--color-averaging!"
+            echo >&2 "ERROR: Invalid value $2 for -g|--color-averaging!"
+            exit 1
          fi
          shift 2
          ;;
@@ -160,7 +162,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             ANTIALIASING="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -A|--antialiasing!"
+            echo >&2 "ERROR: Invalid value $2 for -A|--antialiasing!"
+            exit 1
          fi
          shift 2
          ;;
@@ -168,7 +171,7 @@ while [ $# -gt 0 ] ; do
          LIGHT_DIRECTION="$2"
          if [[ ! "${LIGHT_DIRECTION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($LIGHT_DIRECTION < 0.0) || ($LIGHT_DIRECTION > 360.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${LIGHT_DIRECTION} for -C|--light-direction!"
+            echo >&2 "ERROR: Invalid value ${LIGHT_DIRECTION} for -C|--light-direction!"
             exit 1
          fi
          shift 2
diff --git a/src/GIMP-Scripts/Make-OldPhoto b/src/GIMP-Scripts/Make-OldPhoto
--- a/src/GIMP-Scripts/Make-OldPhoto
+++ b/src/GIMP-Scripts/Make-OldPhoto
@@ -59,15 +59,16 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             DEFOCUS="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -D|--defocus!"
+            echo >&2 "ERROR: Invalid value $2 for -D|--defocus!"
+            exit 1
          fi
          shift 2
          ;;
       -B | --border-size)
          BORDER_SIZE="$2"
          if [[ ! "${BORDER_SIZE}" =~ ^[0-9]+$ ]] ; then
-            echo "ERROR: Invalid value ${BORDER_SIZE} for -B|--border-size!"
-            eyit 1
+            echo >&2 "ERROR: Invalid value ${BORDER_SIZE} for -B|--border-size!"
+            exit 1
          fi
          shift 2
          ;;
@@ -77,7 +78,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             SEPIA="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -S|--sepia!"
+            echo >&2 "ERROR: Invalid value $2 for -S|--sepia!"
+            exit 1
          fi
          shift 2
          ;;
@@ -87,7 +89,8 @@ while [ $# -gt 0 ] ; do
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             MOTTLE="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -M|--mottle!"
+            echo >&2 "ERROR: Invalid value $2 for -M|--mottle!"
+            exit 1
          fi
          shift 2
          ;;
