Parameter naming consistency improvements.

diff --git a/src/GIMP-Scripts/Make-OldPhoto b/src/GIMP-Scripts/Make-OldPhoto
--- a/src/GIMP-Scripts/Make-OldPhoto
+++ b/src/GIMP-Scripts/Make-OldPhoto
@@ -37,13 +37,13 @@ set -eu
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [-d|--defocus on|off] [-b|--bordersize border_size] [-s|--sepia on|off] [-m|--mottle on|off] [-w|--verbose] [-q|--quiet] [-h|--help]"
+   echo >&2 "Usage: $0 input_filename output_filename [-D|--defocus on|off] [-B|--border-size border_size] [-S|--sepia on|off] [-M|--mottle on|off] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o d:b:s:m:wqh --long defocus:,bordersize:,sepia:,mottle:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o D:B:S:M:wqh --long defocus:,border-size:,sepia:,mottle:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
 DEFOCUS="TRUE"
@@ -53,41 +53,41 @@ MOTTLE="FALSE"
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
-      -d | --defocus)
+      -D | --defocus)
          if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             DEFOCUS="TRUE"
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             DEFOCUS="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -d|--defocus!"
+            echo "ERROR: Invalid value $2 for -D|--defocus!"
          fi
          shift 2
          ;;
-      -b | --bordersize)
+      -B | --border-size)
          BORDER_SIZE="$2"
          if [[ ! "${BORDER_SIZE}" =~ ^[0-9]+$ ]] ; then
-            echo "ERROR: Invalid value ${BORDER_SIZE} for -b|--bordersize!"
+            echo "ERROR: Invalid value ${BORDER_SIZE} for -B|--border-size!"
             eyit 1
          fi
          shift 2
          ;;
-      -s | --sepia)
+      -S | --sepia)
          if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             SEPIA="TRUE"
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             SEPIA="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -d|--sepia!"
+            echo "ERROR: Invalid value $2 for -S|--sepia!"
          fi
          shift 2
          ;;
-      -m | --mottle)
+      -M | --mottle)
          if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             MOTTLE="TRUE"
          elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             MOTTLE="FALSE"
          else
-            echo "ERROR: Invalid value $2 for -d|--mottle!"
+            echo "ERROR: Invalid value $2 for -M|--mottle!"
          fi
          shift 2
          ;;
