Added missing parameters.

diff --git a/src/GIMP-Scripts/Make-Clothify b/src/GIMP-Scripts/Make-Clothify
--- a/src/GIMP-Scripts/Make-Clothify
+++ b/src/GIMP-Scripts/Make-Clothify
@@ -37,19 +37,57 @@ set -eu
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [-d|--depth depth] [-w|--verbose] [-q|--quiet] [-h|--help]"
+   echo >&2 "Usage: $0 input_filename output_filename [-x|--blur-x value] [-y|--blur-y value] [-a|--azimut bearing] [-e|--elevation bearing] [-d|--depth depth] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o d:wqh --long depth:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o x:y:a:e:d:wqh --long blur-x:,blur-y:,azimut:,elevation:,depth:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
+BLUR_X=3
+BLUR_Y=3
+AZIMUT=135.0
+ELEVATION=45.0
 DEPTH=5
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
+      -x | --blur-x)
+         BLUR_X="$2"
+         if [[ ! "${BLUR_X}" =~ ^[0-9]+$ ]] || [ "${BLUR_X}" -lt 3 ] || [ "${BLUR_X}" -gt 100 ] ; then
+            echo "ERROR: Invalid value ${BLUR_X} for -x|--blur-x!"
+            exit 1
+         fi
+         shift 2
+         ;;
+      -y | --blur-y)
+         BLUR_Y="$2"
+         if [[ ! "${BLUR_Y}" =~ ^[0-9]+$ ]] || [ "${BLUR_Y}" -lt 3 ] || [ "${BLUR_Y}" -gt 100 ] ; then
+            echo "ERROR: Invalid value ${BLUR_Y} for -y|--blur-y!"
+            eyit 1
+         fi
+         shift 2
+         ;;
+      -a | --azimut)
+         AZIMUT="$2"
+         if [[ ! "${AZIMUT}" =~ ^[0-9]+(|\.[0-9]*)$ ]] || \
+            awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
+            echo "ERROR: Invalid value ${AZIMUT} for -a|--azimut!"
+            exit 1
+         fi
+         shift 2
+         ;;
+      -e | --elevation)
+         ELEVATION="$2"
+         if [[ ! "${ELEVATION}" =~ ^[0-9]+(|\.[0-9]*)$ ]] || \
+            awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
+            echo "ERROR: Invalid value ${ELEVATION} for -e|--elevation!"
+            exit 1
+         fi
+         shift 2
+         ;;
       -d | --depth)
          DEPTH="$2"
          shift 2
@@ -117,6 +155,10 @@ rm -f "${OUTPUT_FILENAME}"
    ; ------ Initialise and load image ---------------------------------------
    ((inputFileName    "${INPUT_FILENAME}")
     (outputFileName   "${OUTPUT_FILENAME}")
+    (blurX            ${BLUR_X})
+    (blurY            ${BLUR_Y})
+    (azimut           ${AZIMUT})
+    (elevation        ${ELEVATION})
     (depth            ${DEPTH})
     (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
     (imageType        (if (not (defined? 'gimp-image-get-active-layer))
@@ -140,11 +182,11 @@ rm -f "${OUTPUT_FILENAME}"
 
    (cond( (not(defined? 'plug-in-bump-map))
       ; New GIMP 3.0 API:
-      (script-fu-clothify image (vector layer) 1 1 135.0 45.0 depth)
+      (script-fu-clothify image (vector layer) blurX blurY azimut elevation depth)
    )
    (else
       ; Old GIMP 2.x API:
-      (script-fu-clothify image layer 1 1 135.0 45.0 depth)
+      (script-fu-clothify image layer blurX blurY azimut elevation depth)
    ))
 
    ; ------ Save result -----------------------------------------------------
@@ -182,7 +224,7 @@ rm -f "${OUTPUT_FILENAME}"
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+) | env LC_ALL=C.UTF-8 HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
