Further parameter naming improvements.

diff --git a/src/GIMP-Scripts/Make-Clothify b/src/GIMP-Scripts/Make-Clothify
--- a/src/GIMP-Scripts/Make-Clothify
+++ b/src/GIMP-Scripts/Make-Clothify
@@ -37,13 +37,13 @@ set -eu
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [-x|--blur-x value] [-y|--blur-y value] [-a|--azimut bearing] [-e|--elevation bearing] [-d|--depth depth] [-w|--verbose] [-q|--quiet] [-h|--help]"
+   echo >&2 "Usage: $0 input_filename output_filename [-X|--blur-x value] [-Y|--blur-y value] [-A|--azimut bearing] [-E|--elevation bearing] [-D|--depth depth] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o x:y:a:e:d:wqh --long blur-x:,blur-y:,azimut:,elevation:,depth:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o X:Y:A:E:D:wqh --long blur-x:,blur-y:,azimut:,elevation:,depth:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
 BLUR_X=3
@@ -54,43 +54,43 @@ DEPTH=5
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
-      -x | --blur-x)
+      -X | --blur-x)
          BLUR_X="$2"
          if [[ ! "${BLUR_X}" =~ ^[0-9]+$ ]] || [ "${BLUR_X}" -lt 3 ] || [ "${BLUR_X}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${BLUR_X} for -x|--blur-x!"
+            echo "ERROR: Invalid value ${BLUR_X} for -X|--blur-x!"
             exit 1
          fi
          shift 2
          ;;
-      -y | --blur-y)
+      -Y | --blur-y)
          BLUR_Y="$2"
          if [[ ! "${BLUR_Y}" =~ ^[0-9]+$ ]] || [ "${BLUR_Y}" -lt 3 ] || [ "${BLUR_Y}" -gt 100 ] ; then
-            echo "ERROR: Invalid value ${BLUR_Y} for -y|--blur-y!"
+            echo "ERROR: Invalid value ${BLUR_Y} for -Y|--blur-y!"
             eyit 1
          fi
          shift 2
          ;;
-      -a | --azimut)
+      -A | --azimut)
          AZIMUT="$2"
          if [[ ! "${AZIMUT}" =~ ^[0-9]*([0-9]|\.[0-9]*)$ ]] || \
             awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${AZIMUT} for -a|--azimut!"
+            echo "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
             exit 1
          fi
          shift 2
          ;;
-      -e | --elevation)
+      -E | --elevation)
          ELEVATION="$2"
          if [[ ! "${ELEVATION}" =~ ^[0-9]*([0-9]|\.[0-9]*)$ ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
-            echo "ERROR: Invalid value ${ELEVATION} for -e|--elevation!"
+            echo "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
          shift 2
          ;;
-      -d | --depth)
+      -D | --depth)
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
-            echo "ERROR: Invalid value ${DEPTH} for -d|--depth!"
+            echo "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
          shift 2
