Improved script, added manpage and shell completion.

diff --git a/src/GIMP-Scripts/Make-Caption b/src/GIMP-Scripts/Make-Caption
--- a/src/GIMP-Scripts/Make-Caption
+++ b/src/GIMP-Scripts/Make-Caption
@@ -42,31 +42,57 @@ set -eu
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [-f|--foreground color] [-b|--background color] [|-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help]"
-   echo >&2 "Example: $0 Caption.png \"Caption Text\" 1024 42 \"Noto Sans Bold\" 60 \"#02266b\" \"#ffd700\" 26"
+   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [|-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o f:b:t:wqh --long foreground:,background:,transparency:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o F:S:f:b:t:wqh --long font-name:,font-size:,foreground:,background:,transparency:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
 COLOR_FOREGROUND="#02266b"   # Dark Blue
 COLOR_BACKGROUND="#ffd700"   # Gold
-TRANSPARENCY=25              # %
+FONT_NAME="Noto Sans Bold"
+FONT_SIZE="50"
+TRANSPARENCY=25              # in %
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
+      -F | --font-name)
+         FONT_NAME="$2"
+         shift 2
+         ;;
+      -S | --font-size)
+         FONT_SIZE="$2"
+         if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
+            echo "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
+            exit 1
+         fi
+         shift 2
+         ;;
       -f | --foreground)
          COLOR_FOREGROUND="$2"
+         if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
+            echo "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
+            exit 1
+         fi
          shift 2
          ;;
       -b | --background)
          COLOR_BACKGROUND="$2"
+         if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
+            echo "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
+            exit 1
+         fi
          shift 2
          ;;
       -t | --transparency)
+         TRANSPARENCY="$2"
+         if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
+            echo "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
+            eyit 1
+         fi
          TRANSPARENCY="$2"
          shift 2
          ;;
@@ -91,25 +117,19 @@ while [ $# -gt 0 ] ; do
   esac
 done
 
-if [ $# -ne 6 ] ; then
+if [ $# -ne 4 ] ; then
    usage 1
 fi
 OUTPUT_FILENAME="$1"
-CAPTION_TEXT="$2"
-CAPTION_WIDTH=$3
-CAPTION_HEIGHT=$4
-FONT_NAME="$5"
-FONT_SIZE=$6
+CAPTION_WIDTH="$2"
+CAPTION_HEIGHT="$3"
+CAPTION_TEXT="$4"
 
-if [[ ! "${TRANSPARENCY}" =~ ^([0-9]+)$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ] ; then
-   echo >&2 "ERROR: Invalid transparency value!"
-   exit 1
-fi
-if [[ ! "${CAPTION_WIDTH}" =~ ^([0-9]+)$ ]] ; then
+if [[ ! "${CAPTION_WIDTH}" =~ ^([0-9]+)$ ]] || [ "${CAPTION_WIDTH}" -lt 1 ]; then
    echo >&2 "ERROR: Invalid caption width!"
    exit 1
 fi
-if [[ ! "${CAPTION_HEIGHT}" =~ ^([0-9]+)$ ]] ; then
+if [[ ! "${CAPTION_HEIGHT}" =~ ^([0-9]+)$ ]] || [ "${CAPTION_HEIGHT}" -lt 1 ]; then
    echo >&2 "ERROR: Invalid caption height!"
    exit 1
 fi
