Improved script.

diff --git a/src/GIMP-Scripts/Resize-with-Cropping b/src/GIMP-Scripts/Resize-with-Cropping
--- a/src/GIMP-Scripts/Resize-with-Cropping
+++ b/src/GIMP-Scripts/Resize-with-Cropping
@@ -32,43 +32,81 @@
 set -eu
 
 
-# ###### Handle arguments ###################################################
+# ###### Main program #######################################################
+
+# ====== Handle arguments ===================================================
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 input output aspect|H:V|HxV|An [new_width] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o b:vqh --long verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
 if [ $# -lt 3 ] ; then
-   echo >&2 "Usage: $0 input output aspect|H:V|HxV|An [new_width]"
-   exit 1
+   usage 1
+fi
+INPUT_FILENAME="$1"
+OUTPUT_FILENAME="$2"
+ASPECT="$3"
+if [ $# -eq 4 ] ; then
+   NEW_WIDTH="$4"
+else
+   NEW_WIDTH=0
 fi
 
-inputFileName="$1"
-outputFileName="$2"
 
-inputImageSize=$(gm identify -format "%wx%h" "$inputFileName")
-
-aspectArg="$3"
-outputAspect=1
-if [[ "$aspectArg" =~ ^([0-9]+\.{0,1}[0-9]*)([:x])([0-9]+\.{0,1}[0-9]*)$ ]] ; then
-   outputAspect=$(LC_NUMERIC=C awk "BEGIN { print ${BASH_REMATCH[1]}/${BASH_REMATCH[3]} }")
+# ====== Prepare output aspect ratio ========================================
+outputAspectRatio=1
+if [[ "${ASPECT}" =~ ^([0-9]+\.{0,1}[0-9]*)([:x])([0-9]+\.{0,1}[0-9]*)$ ]] ; then
+   outputAspectRatio=$(LC_NUMERIC=C awk "BEGIN { print ${BASH_REMATCH[1]}/${BASH_REMATCH[3]} }")
 else
-   if [[ "$aspectArg" =~ ^([0-9]+\.{0,1}[0-9]*)$ ]] ; then
-      outputAspect="${BASH_REMATCH[1]}"
+   if [[ "${ASPECT}" =~ ^([0-9]+\.{0,1}[0-9]*)$ ]] ; then
+      outputAspectRatio="${BASH_REMATCH[1]}"
    else
-      if [[ "$aspectArg" =~ ^[Aa][0-9]$ ]] ; then
-         outputAspect="1.414213562373"   # DIN A<n> is sqrt(2):1 in landscape format
+      if [[ "${ASPECT}" =~ ^[Aa][0-9]$ ]] ; then
+         outputAspectRatio="1.414213562373"   # DIN A<n> is sqrt(2):1 in landscape format
       else
-         echo >&2 "ERROR: Bad aspect specification: $aspectArg!"
+         echo >&2 "ERROR: Bad aspect specification: ${ASPECT}!"
          exit 1
       fi
    fi
 fi
 
-# shellcheck disable=SC2001
-newWidth=$(echo "${inputImageSize}" | sed -e "s/x[0-9]*$//")
-if [ $# -ge 4 ] ; then
-   newWidth="$4"
-   newHeight=$(LC_NUMERIC=C awk "BEGIN { print (${newWidth}/${outputAspect})+0.5 }")
+
+# ====== Obtain image width and height ======================================
+if [ ! -f "${INPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
+   exit 1
 fi
-
-
-# ###### Load image #########################################################
+inputImageSize="$(gm identify -format "%wx%h" "$INPUT_FILENAME")"
 # shellcheck disable=SC2001
 inputWidth=$(echo "${inputImageSize}" | sed -e "s/x[0-9]*$//")
 # shellcheck disable=SC2001
@@ -77,35 +115,46 @@ inputAspect=$(LC_NUMERIC=C awk "BEGIN { print ${inputWidth}/${inputHeight} }")
 if [[ "$inputAspect" =~ ^- ]] ; then
    inputAspect=$(LC_NUMERIC=C awk "BEGIN { print 1/${inputAspect} }")   # Input image is in portrait format => convert aspect
 fi
-# echo "Input: ${inputWidth}*${inputHeight} (${inputAspect})"
+if [ ${VERBOSE} -ne 0 ] ; then
+   echo "Input: ${inputWidth}*${inputHeight} (${inputAspect})"
+fi
+
+if [ "${NEW_WIDTH}" -eq 0 ] ; then
+   # shellcheck disable=SC2001
+   NEW_WIDTH=$(echo "${inputImageSize}" | sed -e "s/x[0-9]*$//")
+fi
+newHeight=$(LC_NUMERIC=C awk "BEGIN { print (${NEW_WIDTH}/${outputAspectRatio})+0.5 }")
 
 
-# ###### Crop image #########################################################
-if [[ "$(LC_NUMERIC=C awk "BEGIN { print ${inputAspect}-${outputAspect} }")" =~ ^- ]] ; then   # inputAspect < outputAspect
+# ====== Crop image =========================================================
+if [[ "$(LC_NUMERIC=C awk "BEGIN { print ${inputAspect}-${outputAspectRatio} }")" =~ ^- ]] ; then   # inputAspect < outputAspectRatio
    croppedInputWidth=${inputWidth}
-   croppedInputHeight=$(LC_NUMERIC=C awk "BEGIN { print int(${croppedInputWidth}/${outputAspect})+0.5 }")
+   croppedInputHeight=$(LC_NUMERIC=C awk "BEGIN { print int(${croppedInputWidth}/${outputAspectRatio})+0.5 }")
 else
    croppedInputHeight=${inputHeight}
-   croppedInputWidth=$(LC_NUMERIC=C awk "BEGIN { print int(${inputHeight}*${outputAspect})+0.5 }")
+   croppedInputWidth=$(LC_NUMERIC=C awk "BEGIN { print int(${inputHeight}*${outputAspectRatio})+0.5 }")
 fi
 cx=$(LC_NUMERIC=C awk "BEGIN { print int(${inputWidth}-${croppedInputWidth})/2+0.5 }")
 cy=$(LC_NUMERIC=C awk "BEGIN { print int(${inputHeight}-${croppedInputHeight})/2+0.5 }")
-# echo "Crop: ${croppedInputWidth}*${croppedInputHeight} [cx=${cx} cy=${cy}] (${outputAspect}:1)"
+if [ ${VERBOSE} -ne 0 ] ; then
+   echo "Crop: ${croppedInputWidth}*${croppedInputHeight} [cx=${cx} cy=${cy}] (${outputAspectRatio}:1)"
+fi
 
 
-# ###### Resize image #######################################################
-# if [ "${newWidth}" != "" ] ; then
-#    echo "Resize: ${newWidth}*${newHeight} + (${outputAspect}:1)"
-# fi
-
-# ###### Run "convert" ######################################################
-rm -f "${outputFileName}"
-gm convert "$inputFileName" \
+# ====== Run "convert" ======================================================
+if [ ${VERBOSE} -ne 0 ] ; then
+   if [ "${NEW_WIDTH}" != "" ] ; then
+      echo "Resize: ${NEW_WIDTH}*${newHeight} + (${outputAspectRatio}:1)"
+   fi
+fi
+rm -f "${OUTPUT_FILENAME}"
+gm convert "$INPUT_FILENAME" \
    -crop "${croppedInputWidth}"x"${croppedInputHeight}"+"${cx}"+"${cy}" \
-   -resize "${newWidth}"x"${newHeight}" \
+   -resize "${NEW_WIDTH}"x"${newHeight}" \
    +repage \
-   "${outputFileName}"
+   "${OUTPUT_FILENAME}"
 
-# echo "Done!"
-
-# gm identify "${outputFileName}"
+if [ ${VERBOSE} -ne 0 ] ; then
+   echo -n "Done: "
+   gm identify "${OUTPUT_FILENAME}"
+fi
