Improved scripts.

diff --git a/src/GIMP-Scripts/run-tests b/src/GIMP-Scripts/run-tests
--- a/src/GIMP-Scripts/run-tests
+++ b/src/GIMP-Scripts/run-tests
@@ -75,20 +75,22 @@ show-script ()
 
 # ====== Find tools =========================================================
 if ! command -v print-utf8 2>/dev/null ; then
-   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed!"
-   echo >&2 "Try this:"
-   echo >&2 "* Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
-   echo >&2 "           sudo apt install -y td-system-tools"
-   echo >&2 "* Fedora:  sudo dnf copr enable -y dreibh/ppa"
-   echo >&2 "           sudo dnf install -y td-system-tools"
-   echo >&2 "* FreeBSD: sudo pkg install -y td-system-tools"
+   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed! Try:"
+   echo >&2 "* Ubuntu/Debian: sudo apt-add-repository -sy ppa:dreibh/ppa"
+   echo >&2 "                 sudo apt install -y td-system-tools"
+   echo >&2 "* Fedora:        sudo dnf copr enable -y dreibh/ppa"
+   echo >&2 "                 sudo dnf install -y td-system-tools"
+   echo >&2 "* FreeBSD:       sudo pkg install -y td-system-tools"
    exit 1
 fi
 if ! command -v figlet 2>/dev/null ; then
    echo >&2 "ERROR: Figlet is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y figlet"
-   echo >&2 "* Fedora:  sudo dnf install -y figlet"
-   echo >&2 "* FreeBSD: sudo pkg install -y figlet"
+   echo >&2 "* Ubuntu/Debian: sudo apt install -y figlet"
+   echo >&2 "* Fedora:        sudo dnf install -y figlet"
+   echo >&2 "* FreeBSD:       sudo pkg install -y figlet"
+   echo >&2 "* NetBSD:        sudo pkgin -y install figlet"
+   echo >&2 "* OpenBSD:       sudo pkg_add figlet"
+   echo >&2 "* Apple:         brew install figlet"
    exit 1
 fi
 
@@ -147,8 +149,13 @@ show-script "gs-glossytext"
    --outline-size 16                         \
    --blend-gradient-text "Brushed Aluminium" \
    --blend-gradient-outline "Golden" || exit-failed
+if ./gs-list-fonts | grep -q "URW Gothic L Book Oblique" ; then
+   fontName="URW Gothic L Book Oblique"
+else
+   fontName="URW Gothic Book Oblique"
+fi
 ./gs-glossytext NorNet3.png "NorNet Testbed" \
-   -F "URW Gothic Book Oblique"              \
+   -F "${fontName}"                          \
    -S 128                                    \
    -O 5                                      \
    -G "Brushed Aluminium"                    \
