Improved package installation hints.

diff --git a/src/GIMP-Scripts/run-tests b/src/GIMP-Scripts/run-tests
--- a/src/GIMP-Scripts/run-tests
+++ b/src/GIMP-Scripts/run-tests
@@ -97,6 +97,19 @@ if ! command -v figlet >/dev/null ; then
    echo >&2 "* Apple:         brew install figlet"
    exit 1
 fi
+if ! command -v gm >/dev/null ; then
+   echo >&2 "ERROR: GraphicsMagick is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y graphicsmagick"
+   echo >&2 " * Fedora:        sudo dnf install -y GraphicsMagick"
+   echo >&2 " * SuSE:          sudo zypper install -y GraphicsMagick"
+   echo >&2 " * Alpine:        sudo apk add graphicsmagick"
+   echo >&2 " * FreeBSD:       sudo pkg install -y GraphicsMagick"
+   echo >&2 " * NetBSD:        sudo pkgin -y install GraphicsMagick"
+   echo >&2 " * OpenBSD:       sudo pkg_add GraphicsMagick"
+   echo >&2 " * Solaris:       sudo pkg install graphicsmagick"
+   echo >&2 " * Apple:         brew install GraphicsMagick"
+   exit 1
+fi
 
 
 # ====== gs-test-gimp ==========================================================
