Improved script.

diff --git a/po/run-ai-translation b/po/run-ai-translation
--- a/po/run-ai-translation
+++ b/po/run-ai-translation
@@ -32,18 +32,56 @@
 set -euo pipefail
 
 
-MODEL="aya-expanse:32b"   # "aya-expanse:32b" "deepseek-r1:671b" "translategemma:27b" "ministral-3:14b" "qwen3.5:122b" "qwen3.6:35b"
+MODEL="qwen3.6:35b"   # "aya-expanse:32b" "deepseek-r1:671b" "translategemma:27b" "ministral-3:14b" "qwen3.5:122b" "qwen3.6:35b"
+CONTEXT="You are an expert technical translator localizing a Unix (Linux, FreeBSD) system administration scripts. The target audience consists of technical users and sysadmins. Maintain standard Unix terminology in the target language for concepts like \"operating system\", \"network\", \"processes\", \"processor\", \"kernel\", \"swap\", \"uptime\", \"kernel\", \"load\", and \"mount points\", and topics like X.509 certificates, Unix epoch, as well as GIMP, GraphicsMagick, image processing. Strictly preserve all C-style formatting variables (such as \"%s\", \"%d\", \"%'d\", \"%1.1f\", \"%'6.0f\", \"%'5.1f\"), C-style escaping in the format strings (such as \"%%\" for the percent character), and Bash shell-style variables (such as \${now}, \${os_label}, \${system_release}, \${system_cores}, \${system_machine}, \${processesString}, \${usersString}), exactly.
+Particularly, exactly preserve the formatting pattern \"%'d\". Return ONLY the valid translation structure. Do not include any conversational text, greetings, explanations, or markdown notes. Output exactly what the parser expects."
 
 LANGUAGES="ar cs de el en es fa fr he hi id it ja ko nl pl pt ro ru tr uk vi zh"   # for "aya-expanse:32b"
 # LANGUAGES="ar be bg bn cs da de el en es et fa fi fr ga he hi hr hu is it ja ko lt lv mi mt nb nl nn no pl pt ro ru sk sl sq sr sv ta th tr uk zh"
-LANGUAGES="ar da sv he ru" # "da sv he ru"
+LANGUAGES="ar da sv he ru"
 
 PROGRAMS="System-Info"
-CONTEXT="You are an expert technical translator localizing a Unix (Linux, FreeBSD) system administration scripts. The target audience consists of technical users and sysadmins. Maintain standard Unix terminology in the target language for concepts like \"operating system\", \"network\", \"processes\", \"processor\", \"kernel\", \"swap\", \"uptime\", \"kernel\", \"load\", and \"mount points\". Strictly preserve all C-style formatting variables (such as \"%s\", \"%d\", \"%1.1f\", \"%'6.0f\", \"%'5.1f\"), C-style escaping in the format strings (such as \"%%\" for the percent character), and Bash shell-style variables (such as \${now}, \${os_label}, \${system_release}, \${system_cores}, \${system_machine}, \${processesString}, \${usersString}), exactly."
+
+
+# ###### Helper function to show program information #########################
+show-program ()
+{
+   local program="$1"
+
+   "${PRINT_UTF8}" -n -s "\e[1;36m█" "▀" "█\e[0m" ;
+   "${FIGLET}" -w "${COLUMNS}" "$(basename "${program}")" | "${PRINT_UTF8}" -n -C "\e[1;36m█\e[25m" "█\e[0m" ;
+   "${PRINT_UTF8}" -n -s "\e[1;36m█" "▄" "█\e[0m"
+}
+
 
 
 # ###### Main program #######################################################
+
+# ====== Find locations of Python interpreter, MyPy, and tools ==============
+PRINT_UTF8="$(which print-utf8 2>/dev/null || true)"
+if [ ! -x "${PRINT_UTF8}" ] ; then
+   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed!"
+   echo >&2 "Try this:"
+   echo >&2 "* Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
+   echo >&2 "           sudo apt install -y td-system-tools"
+   echo >&2 "* Fedora:  sudo dnf copr enable -y dreibh/ppa"
+   echo >&2 "           sudo dnf install -y td-system-tools"
+   echo >&2 "* FreeBSD: sudo pkg install -y td-system-tools"
+   exit 1
+fi
+FIGLET="$(which figlet 2>/dev/null || true)"
+if [ ! -x "${FIGLET}" ] ; then
+   echo >&2 "ERROR: Figlet is not installed!"
+   echo >&2 "* Ubuntu:  sudo apt install -y figlet"
+   echo >&2 "* Fedora:  sudo dnf install -y figlet"
+   echo >&2 "* FreeBSD: sudo pkg install -y figlet"
+   exit 1
+fi
+
+# ====== Translate PO files =================================================
 for program in ${PROGRAMS} ; do
+   show-program "${program}"
+
    for language in ${LANGUAGES} ; do
 
       # ====== Prepare initial PO file ======================================
@@ -73,8 +111,8 @@ for program in ${PROGRAMS} ; do
          --model "${MODEL}" \
          --folder . \
          --lang   "${language}" \
-         --bulk --bulksize 15 \
          --ollama-timeout 300 \
+         --bulk --bulksize 16 \
          --verbose \
          --default-context "${CONTEXT}"
 
