Improved messages.

diff --git a/src/Reset-Machine-ID b/src/Reset-Machine-ID
--- a/src/Reset-Machine-ID
+++ b/src/Reset-Machine-ID
@@ -49,14 +49,14 @@ while [ $# -gt 0 ] ; do
       YES_TO_ALL=1
       applyChanges="yes"
    elif [ "$1" == "--hostname" ] || [ "$1" == "-H" ] || [ "$1" == "-hostname" ] ; then
-
+      hostname="$2"
+      shift
       if [[ ! "$2" =~ ^([a-zA-Z][a-zA-Z0-9-]+\.)*[a-zA-Z][a-zA-Z0-9-]*$ ]] ; then
-         echo >&2 "$(eval_gettext "ERROR: Invalid hostname:") $2!"
+         echo >&2 "$(eval_gettext "ERROR: Invalid hostname \${hostname}!")"
          exit 1
       fi
-      NEW_HOSTNAME_FQDN="$2"
+      NEW_HOSTNAME_FQDN="${hostname}"
       NEW_HOSTNAME="${NEW_HOSTNAME_FQDN//.*/}"
-      shift
    elif [ "$1" == "--skip-ssh-configuration" ] || [ "$1" == "-S" ] || [ "$1" == "-skip-ssh-configuration" ] ; then
       SKIP_SSH_CONFIGURATION=1
    elif [ "$1" == "--skip-ssh-key-replacement" ] || [ "$1" == "-S" ] || [ "$1" == "-skip-key-replacement" ] ; then
@@ -198,11 +198,11 @@ EOF
 
 
    # ====== Apply ssh_config updates ========================================
-   gettext "Suggested ssh_config change:"
+   gettext "Suggested ssh_config changes:"
    echo ""
    if ! diff --color=always ssh_config ssh_config.suggested ; then
       if [ ${YES_TO_ALL} -ne 1 ] ; then
-         echo -en "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Apply suggested ssh_config?") [yes/no]?\x1b[0m "
+         echo -en "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Apply suggested ssh_config changes?") [yes/no]?\x1b[0m "
          read -er applyChanges
       fi
       if [ "${applyChanges}" == "yes" ] || [ "${applyChanges}" == "y" ] ; then
@@ -277,12 +277,12 @@ EOF
 
 
    # ====== Apply sshd_config updates =======================================
-   gettext "Suggested sshd_config change:"
+   gettext "Suggested sshd_config changes:"
    echo ""
    diff --color=always sshd_config sshd_config.suggested || differences=$(( differences+1))
    if [ ${differences} -gt 0 ] ; then
       if [ ${YES_TO_ALL} -ne 1 ] ; then
-         echo -en "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Replace sshd_config?") [yes/no]?\x1b[0m "
+         echo -en "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Apply suggested sshd_config changes?") [yes/no]?\x1b[0m "
          read -er applyChanges
       fi
       if [ "${applyChanges}" == "yes" ] || [ "${applyChanges}" == "y" ] ; then
@@ -314,7 +314,7 @@ if [ ${SKIP_SSH_KEY_REPLACEMENT} -eq 0 ] && [ -d /etc/ssh ] ; then
    if [ "${applyChanges}" == "yes" ] || [ "${applyChanges}" == "y" ] ; then
       backupDirectory="backup-$(env LANG=C date +%FT%H:%M:%S)"
 
-      echo -e "\x1b[32m$(date +%FT%H:%M:%S): $(eval_gettext "Making backup of keys in \${backupDirectory} ...")\x1b[0m"
+      echo -e "\x1b[32m$(date +%FT%H:%M:%S): $(eval_gettext "Making backup of current keys in \${backupDirectory} ...")\x1b[0m"
       mkdir "${backupDirectory}/"
       find . -maxdepth 1 -name "ssh_host_*_key*" -print0 | xargs -0 -n1 -I § -r mv § "${backupDirectory}/"
       find . -maxdepth 1 -name "ssh_host_key*"   -print0 | xargs -0 -n1 -I § -r mv § "${backupDirectory}/"
