Fixed options processing.

diff --git a/src/Reset-Machine-ID b/src/Reset-Machine-ID
--- a/src/Reset-Machine-ID
+++ b/src/Reset-Machine-ID
@@ -66,18 +66,6 @@ select-ssh-options ()
    echo "${selectedOptions}"
 }
 
-sshCiphers=$(select-ssh-options       Ciphers       cipher   aes256-gcm@openssh.com chacha20-poly1305@openssh.com)
-sshMACs=$(select-ssh-options          MACs          mac      hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com)
-sshKexAlgorithms=$(select-ssh-options KexAlgorithms kex      curve25519-sha256@libssh.org diffie-hellman-group16-sha512 diffie-hellman-group18-sha512)
-sshPubkeyAcceptedKeyTypes=$(select-ssh-options       PubkeyAcceptedKeyTypes    PubkeyAcceptedKeyTypes    ssh-ed25519-cert-v01@openssh.com ssh-ed25519 rsa-sha2-512-cert-v01@openssh.com ssh-rsa-cert-v01@openssh.com rsa-sha2-512)
-sshHostbasedAcceptedKeyTypes=$(select-ssh-options    HostbasedAcceptedKeyTypes HostbasedAcceptedKeyTypes ssh-ed25519-cert-v01@openssh.com ssh-ed25519 ssh-rsa-cert-v01@openssh.com ssh-rsa)
-sshHostKeyAlgorithms=$(select-ssh-options            HostKeyAlgorithms         HostKeyAlgorithms         ssh-ed25519-cert-v01@openssh.com ssh-ed25519 ssh-rsa-cert-v01@openssh.com ssh-rsa)
-if [ "${sshPubkeyAcceptedKeyTypes}" != "" ] ; then
-   newSSH=""
-else
-   newSSH="# "   # SSH version is too old!
-fi
-
 
 
 # ###### Main program #######################################################
@@ -219,6 +207,27 @@ fi
 
 # ====== SSH configuration ==================================================
 if [ ${SKIP_SSH_CONFIGURATION} -eq 0 ] && [ -d /etc/ssh ] ; then
+
+   sshCiphers=$(select-ssh-options       Ciphers       cipher   aes256-gcm@openssh.com chacha20-poly1305@openssh.com)
+   sshMACs=$(select-ssh-options          MACs          mac      hmac-sha2-512-etm@openssh.com hmac-sha2-256-etm@openssh.com)
+   sshKexAlgorithms=$(select-ssh-options KexAlgorithms kex      curve25519-sha256@libssh.org diffie-hellman-group16-sha512 diffie-hellman-group18-sha512)
+   sshPubkeyAcceptedKeyTypes=$(select-ssh-options       PubkeyAcceptedKeyTypes    PubkeyAcceptedKeyTypes    ssh-ed25519-cert-v01@openssh.com ssh-ed25519 rsa-sha2-512-cert-v01@openssh.com ssh-rsa-cert-v01@openssh.com rsa-sha2-512)
+   sshHostbasedAcceptedKeyTypes=$(select-ssh-options    HostbasedAcceptedKeyTypes HostbasedAcceptedKeyTypes ssh-ed25519-cert-v01@openssh.com ssh-ed25519 ssh-rsa-cert-v01@openssh.com ssh-rsa)
+   sshHostKeyAlgorithms=$(select-ssh-options            HostKeyAlgorithms         HostKeyAlgorithms         ssh-ed25519-cert-v01@openssh.com ssh-ed25519 ssh-rsa-cert-v01@openssh.com ssh-rsa)
+   if [ "${sshPubkeyAcceptedKeyTypes}" != "" ] ; then
+      newSSH=""
+   else
+      newSSH="# "   # SSH version is too old!
+   fi
+   if [ "${sshCiphers}" == "" ] || \
+      [ "${sshMACs}" == "" ] || \
+      [ "${sshKexAlgorithms}" == "" ] ; then
+      echo >&2 "ERROR: Something seems to be wrong!"
+      echo >&2 "sshCiphers=${sshCiphers}"
+      echo >&2 "sshMACs=${sshMACs}"
+      echo >&2 "sshKexAlgorithms=${sshKexAlgorithms}"
+      exit 1
+   fi
 
    cd /etc/ssh || exit
    echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Checking SSH configuration ...")\x1b[0m"
