Started to add host name configuration.

diff --git a/src/Reset-Machine-ID b/src/Reset-Machine-ID
--- a/src/Reset-Machine-ID
+++ b/src/Reset-Machine-ID
@@ -47,11 +47,69 @@ show-keys ()
 
 # ====== Handle arguments ===================================================
 YES_TO_ALL=0
+OLD_HOSTNAME_FQDN="$(hostname -f)"
+OLD_HOSTNAME="${OLD_HOSTNAME_FQDN//.*/}"
+NEW_HOSTNAME_FQDN="${OLD_HOSTNAME_FQDN}"
 applyChanges=""
 if [ "$1" == "--yes-to-all-i-am-really-sure" ] || [ "$1" == "-yes-to-all-i-am-really-sure" ] ; then
    YES_TO_ALL=1
    applyChanges="yes"
+elif [ "$1" == "--hostname" ] || [ "$1" == "-H" ] || [ "$1" == "-hostname" ] ; then
+   if [[ ! "$2" =~ ^([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]+$ ]] ; then
+      echo >&2 "ERROR: Bad hostname $2!"
+      exit 1
+   fi
+   NEW_HOSTNAME_FQDN="$2"
+   NEW_HOSTNAME="${NEW_HOSTNAME_FQDN//.*/}"
+   shift
 fi
+
+
+# ====== Change hostname ====================================================
+# if [ "${OLD_HOSTNAME_FQDN}" != "${NEW_HOSTNAME_FQDN}" ] ; then
+#    if [ ${YES_TO_ALL} -ne 1 ] ; then
+#       echo -en "\x1b[33mChange hostname from ${OLD_HOSTNAME_FQDN} to ${NEW_HOSTNAME_FQDN}? [yes/no]?\x1b[0m "
+#       read -er applyChanges
+#    fi
+#    if [ "${applyChanges}" = "yes" ] || [ "${applyChanges}" = "y" ] ; then
+
+
+      # ====== Update /etc/hostname or /etc/rc.conf =========================
+
+
+      # ====== Update /etc/hosts ============================================
+      while read -r line ; do
+
+         if [[ "${line}" =~ ^(127\.0.\0.1|127\.0\.1\.1|::1)[[:blank:]] ]] ; then
+            currentNames="$(echo "${line}" | sed -e 's/^[0-9a-fA-F\.:]*[[:blank:]]*//g' -e 's/[[:blank:]][[:blank:]]*/\n/g' | sort -u)"
+            newNames="${NEW_HOSTNAME_FQDN}"
+            if [ "${NEW_HOSTNAME}" != "${NEW_HOSTNAME_FQDN}" ] ; then
+               newNames="${newNames} ${NEW_HOSTNAME}"
+            fi
+            for currentName in ${currentNames} ; do
+               if [[ "${currentName}" =~ ^(localhost|localhost[46]|ip6-localhost|ip6-loopback)(\..*|)$ ]] ; then
+                  newNames="${newNames} ${currentName}"
+               #else
+                  #echo >&2 "${currentName} DDD"
+               fi
+
+            done
+
+            line="$(echo "${line}" | sed -e "s/\([[:blank:]][[:blank:]]*\).*$/\1${newNames}/g")"
+
+         elif [[ "${line}" =~ ^(([0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3})|((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:)))(%.+)?)[[:blank:]] ]] ; then
+            line="$(echo "${line}" | sed -e "s/${OLD_HOSTNAME_FQDN}/${NEW_HOSTNAME_FQDN}/g")"
+         fi
+
+         echo "${line}"
+
+      done </etc/hosts >hosts.updated
+      diff --color /etc/hosts hosts.updated
+
+      exit 1
+
+#    fi
+# fi
 
 
 # ====== Reset machine ID ===================================================
