System-Maintenance updates: * Added gettext support * Removed obsolete options for Grub update and interface mapping removal.

diff --git a/src/System-Maintenance b/src/System-Maintenance
--- a/src/System-Maintenance
+++ b/src/System-Maintenance
@@ -21,18 +21,26 @@
 # Bash options:
 set -e
 
+
+export TEXTDOMAIN="System-Maintenance"
+# export TEXTDOMAINDIR="${PWD}/locale"   # Default: "/usr/share/locale"
+
+# shellcheck disable=SC1091
+. gettext.sh
+
+
 INTERACTIVE_KERNEL_REMOVAL=0
-DONT_TOUCH_GRUB=0
-KEEP_INTERFACE_MAPPINGS=1
+# DONT_TOUCH_GRUB=0
+# KEEP_INTERFACE_MAPPINGS=1
 while [ $# -gt 0 ] ; do
    if [ "$1" = "-interactive-kernel-removal" ] || [ "$1" = "-k" ] ; then
       INTERACTIVE_KERNEL_REMOVAL=1
-   elif [ "$1" = "-dont-touch-grub" ] || [ "$1" = "-g" ] ; then
-      DONT_TOUCH_GRUB=1
-   elif [ "$1" = "-dont-keep-interface-mappings" ] || [ "$1" = "-M" ] ; then
-      KEEP_INTERFACE_MAPPINGS=0
+   # elif [ "$1" = "-dont-touch-grub" ] || [ "$1" = "-g" ] ; then
+   #    DONT_TOUCH_GRUB=1
+   # elif [ "$1" = "-dont-keep-interface-mappings" ] || [ "$1" = "-M" ] ; then
+   #    KEEP_INTERFACE_MAPPINGS=0
    else
-      echo 2>&1 "Usage: $0 [-interactive-kernel-removal|-k] [-dont-touch-grub|-g] [-dont-keep-interface-mappings|-M]"
+      echo 2>&1 "$(eval_gettext "Usage: ") $0 [-interactive-kernel-removal|-k] [-dont-touch-grub|-g] [-dont-keep-interface-mappings|-M]"
       exit 1
    fi
    shift
@@ -57,13 +65,13 @@ fi
 
 # ====== Stop AutoFS ========================================================
 if [ -e /etc/init.d/autofs ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Stopping AutoFS service ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Stopping AutoFS service ...")\x1b[0m"
    sudo service autofs stop >/dev/null 2>&1 || true
 fi
 
 # ====== dpkg package fixes =================================================
 if [ "${variant}" = "Debian" ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Applying package fixes, if necessary ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Applying package fixes, if necessary ...")\x1b[0m"
    sudo DEBIAN_FRONTEND=noninteractive dpkg --configure -a | sudo tee -a /tmp/install.log &
    wait
    cat /tmp/install.log
@@ -71,10 +79,10 @@ fi
 
 # ====== Update package repositories ========================================
 if [ "${variant}" = "Debian" ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Updating package repositories ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Updating package repositories ...")\x1b[0m"
    sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
 elif [ "${variant}" = "FreeBSD" ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Updating package repositories ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Updating package repositories ...")\x1b[0m"
    sudo env PAGER=cat freebsd-update fetch
    sudo env ASSUME_ALWAYS_YES=yes pkg-static update
    if [ -x /usr/sbin/portsnap ] ; then
@@ -84,7 +92,7 @@ fi
 
 # ====== apt-get package fixes ==============================================
 if [ "${variant}" = "Debian" ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Installing missing dependencies, if necessary ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Installing missing dependencies, if necessary ...")\x1b[0m"
    sudo DEBIAN_FRONTEND=noninteractive nohup apt-get install -f -y -q \
       -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef"  | sudo tee -a /tmp/install.log &
    wait
@@ -92,7 +100,7 @@ if [ "${variant}" = "Debian" ] ; then
 fi
 
 # ====== system update ======================================================
-echo -e "\x1b[34m$(date +%FT%H:%M:%S): Installing updates ...\x1b[0m"
+echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Installing updates ...")\x1b[0m"
 if [ "${variant}" = "Debian" ] ; then
    # ------ Download --------------------------------------
    sudo DEBIAN_FRONTEND=noninteractive nohup apt-get dist-upgrade -yd -q \
@@ -142,7 +150,7 @@ elif [ "${variant}" = "FreeBSD" ] ; then
 fi
 
 # ====== Auto-remove ========================================================
-echo -e "\x1b[34m$(date +%FT%H:%M:%S): Cleaning up ...\x1b[0m"
+echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Cleaning up ...")\x1b[0m"
 if [ "${variant}" = "Debian" ] ; then
    # ------ Remove unnecessary dependencies ---------------
    sudo DEBIAN_FRONTEND=noninteractive nohup apt-get autoremove -y -q \
@@ -175,15 +183,15 @@ fi
 
 # ====== Remove obsolete kernel packages ====================================
 if [ "${variant}" = "Debian" ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Removing obsolete kernels ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Removing obsolete kernels ...")\x1b[0m"
 
    kernelType=$(uname -r | sed 's/\([0-9]*.[0-9]*.[0-9]*\|[0-9]*.[0-9]*.[0-9]*.-[0-9]*\)-\([a-zA-Z0-9\.+]\)/\2/')
    kernelBootVersion=$(uname -r | sed s/-"${kernelType}"//)
    kernelDiskVersion=$(find /boot -name "vmlinuz-*-${kernelType}" | sort -rV | head -n1 | sed -e "s/\/boot\/vmlinuz-//" -e "s/-${kernelType}//")
 
-   echo "Kernel Type:         ${kernelType}"
-   echo "Kernel Boot Version: ${kernelBootVersion}"
-   echo "Kernel Disk Version: ${kernelDiskVersion}"
+   echo "$(eval_gettext "Kernel Type:        ") ${kernelType}"
+   echo "$(eval_gettext "Kernel Boot Version:") ${kernelBootVersion}"
+   echo "$(eval_gettext "Kernel Disk Version:") ${kernelDiskVersion}"
 
    packageVersionsFile=$(mktemp)
    apt-show-versions | awk '{ print $1 }' | sed -e "s/:.*$//g" -e "s/\/.*$//g" | sort >"${packageVersionsFile}"
@@ -252,10 +260,10 @@ if [ "${variant}" = "Debian" ] ; then
 
    if [ "$(echo "${toBeRemoved}" | xargs -n1 | grep -v ".*+$")" != "" ] ; then
 
-      echo -e "To be removed:\x1b[31m"
+      echo -e "$(eval_gettext "To be removed:")\x1b[31m"
       echo "${toBeRemoved}" | xargs -n1 | grep -v ".*+$" || true
       echo -en "\x1b[0m"
-      echo -e "To be kept:\x1b[32m"
+      echo -e "$(eval_gettext "To be kept:")\x1b[32m"
       echo "${toBeRemoved}" | xargs -n1 | grep ".*+$" | sed -e "s/+$//g" || true
       echo -en "\x1b[0m"
 
@@ -279,46 +287,45 @@ if [ "${variant}" = "Debian" ] ; then
 fi
 
 # ====== Fix bootloader =====================================================
-if [ ${DONT_TOUCH_GRUB} -eq 0 ] ; then
-   if [ "${variant}" == "Ubuntu" ] || [ "${variant}" == "Debian" ] ; then
-      if [ -x /usr/sbin/update-grub ] && [ -x /usr/sbin/grub-install ] ; then
-         echo -e "\x1b[34m$(date +%FT%H:%M:%S): Ensuring that Grub configuration is up-to-date ...\x1b[0m"
-         sudo nohup </dev/null /usr/sbin/grub-install /dev/sda  | sudo tee -a /tmp/install.log || true
-         if ! sudo nohup </dev/null /usr/sbin/update-grub | sudo tee -a /tmp/install.log ; then
-            cat /tmp/install.log
-            echo >&2 "ERROR: Something went wrong with update-grub!"
-            exit 1
-         fi
-         cat /tmp/install.log
-      fi
-   elif [ "${variant}" == "Fedora" ] ; then
-      echo -e "\x1b[34m$(date +%FT%H:%M:%S): Ensuring that Grub configuration is up-to-date ...\x1b[0m"
-      sudo nohup </dev/null grub2-mkconfig -o "$(readlink -e /etc/grub2.cfg)"  | sudo tee -a /tmp/install.log || true
-      if ! sudo nohup </dev/null grub2-install /dev/sda | sudo tee -a /tmp/install.log ; then
-         cat /tmp/install.log
-         echo >&2 "ERROR: Something went wrong with grub2-install!"
-         cat /tmp/install.log
-         exit 1
-      fi
-      cat /tmp/install.log
-   fi
-fi
+# if [ ${DONT_TOUCH_GRUB} -eq 0 ] ; then
+#    if [ "${variant}" == "Ubuntu" ] || [ "${variant}" == "Debian" ] ; then
+#       if [ -x /usr/sbin/update-grub ] && [ -x /usr/sbin/grub-install ] ; then
+#          echo -e "\x1b[34m$(date +%FT%H:%M:%S): Ensuring that Grub configuration is up-to-date ...\x1b[0m"
+#          sudo nohup </dev/null /usr/sbin/grub-install /dev/sda  | sudo tee -a /tmp/install.log || true
+#          if ! sudo nohup </dev/null /usr/sbin/update-grub | sudo tee -a /tmp/install.log ; then
+#             cat /tmp/install.log
+#             echo >&2 "ERROR: Something went wrong with update-grub!"
+#             exit 1
+#          fi
+#          cat /tmp/install.log
+#       fi
+#    elif [ "${variant}" == "Fedora" ] ; then
+#       echo -e "\x1b[34m$(date +%FT%H:%M:%S): Ensuring that Grub configuration is up-to-date ...\x1b[0m"
+#       sudo nohup </dev/null grub2-mkconfig -o "$(readlink -e /etc/grub2.cfg)"  | sudo tee -a /tmp/install.log || true
+#       if ! sudo nohup </dev/null grub2-install /dev/sda | sudo tee -a /tmp/install.log ; then
+#          cat /tmp/install.log
+#          echo >&2 "ERROR: Something went wrong with grub2-install!"
+#          cat /tmp/install.log
+#          exit 1
+#       fi
+#       cat /tmp/install.log
+#    fi
+# fi
 
 # ====== Refresh snaps ======================================================
 if [ -x /usr/bin/snap ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Refreshing snaps ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Refreshing snaps ...")\x1b[0m"
    sudo /usr/bin/snap refresh || true
 fi
 
 # ====== Firmware updates ===================================================
 if [ -x /usr/bin/fwupdmgr ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Checking for firmware updates ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Checking for firmware updates ...")\x1b[0m"
    sudo /usr/bin/fwupdmgr update || true
 fi
 
 # ====== apt-file cache update ==============================================
-# Cache updates
-echo -e "\x1b[34m$(date +%FT%H:%M:%S): Updating caches ...\x1b[0m"
+echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Updating caches ...")\x1b[0m"
 if [ "${variant}" = "Debian" ] ; then
    if [ -x /usr/bin/apt-file ] ; then
       sudo /usr/bin/apt-file update >/dev/null
@@ -337,30 +344,30 @@ else
 fi
 
 # ====== Delete /etc/udev/rules.d/70-persistent-net.rules ===================
-if [ "${variant}" = "Debian" ] ; then
-   if [ $KEEP_INTERFACE_MAPPINGS -eq 0 ] ; then
-      echo -e "\x1b[34m$(date +%FT%H:%M:%S): Checking interface mapping ...\x1b[0m"
-
-      # Ensure that new interfaces get mapped!
-      sudo udevadm trigger --action=add
-
-      if ! ifconfig eth0 >/dev/null 2>&1 ; then
-         echo "eth0 does not exist => Deleting /etc/udev/rules.d/70-persistent-net.rules"
-         rm -f /etc/udev/rules.d/70-persistent-net.rules
-         echo "*** Interfaces should be remapping during next boot! ***"
-      fi
-   fi
-fi
+# if [ "${variant}" = "Debian" ] ; then
+#    if [ $KEEP_INTERFACE_MAPPINGS -eq 0 ] ; then
+#       echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Checking interface mapping ...")\x1b[0m"
+#
+#       # Ensure that new interfaces get mapped!
+#       sudo udevadm trigger --action=add
+#
+#       if ! ifconfig eth0 >/dev/null 2>&1 ; then
+#          echo "eth0 does not exist => Deleting /etc/udev/rules.d/70-persistent-net.rules"
+#          rm -f /etc/udev/rules.d/70-persistent-net.rules
+#          echo "*** Interfaces should be remapping during next boot! ***"
+#       fi
+#    fi
+# fi
 
 # ====== Start AutoFS =======================================================
 if [ -e /etc/init.d/autofs ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Starting AutoFS service ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Starting AutoFS service ...")\x1b[0m"
    sudo service autofs start >/dev/null 2>&1 || true
 fi
 
 # ====== Fix time ===========================================================
 if [ -e /etc/ntp.conf ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Synchronising system time ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Synchronising system time ...")\x1b[0m"
    for ntpServiceName in ntp ntpd ; do
       sudo service ${ntpServiceName} stop >/dev/null 2>&1 || true
    done
@@ -393,11 +400,11 @@ fi
 
 # ====== SSD trimming =======================================================
 if [ -x /sbin/fstrim ] || [ -x /usr/sbin/fstrim ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Running fstrim ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Running fstrim ...")\x1b[0m"
    sudo fstrim -a -v 2>/dev/null || ( sudo fstrim -v / && sudo fstrim -v /home ) || true
 fi
 if [ -x /sbin/zpool ] || [ -x /usr/sbin/zpool ] ; then
-   echo -e "\x1b[34m$(date +%FT%H:%M:%S): Running zpool trim ...\x1b[0m"
+   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Running zpool trim ...")\x1b[0m"
    zpools=$(zpool list -H | cut -f1)
    for zpool in ${zpools} ; do
       echo "${zpool}"
@@ -406,7 +413,7 @@ if [ -x /sbin/zpool ] || [ -x /usr/sbin/zpool ] ; then
 fi
 
 # ====== Done! ==============================================================
-echo -e "\x1b[34m$(date +%FT%H:%M:%S): Done!\x1b[0m"
+echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Done!")\x1b[0m"
 
 # ====== Finally, show project package versions =============================
 filterScripts=""
