Added tests.

diff --git a/src/text-block-test b/src/text-block-test
--- a/src/text-block-test
+++ b/src/text-block-test
@@ -6,7 +6,8 @@ RUN=""
 # RUN="valgrind "
 
 make text-block
-for mode in cat extract remove ; do
+insertFile="text-block-tests/insert.txt"
+for mode in cat extract remove replace ; do
    for o1 in include-tags exclude-tags ; do
       for o2 in tags-only full-tag-lines ; do
          for test in simple ; do
@@ -16,13 +17,18 @@ for mode in cat extract remove ; do
             echo >&2 -e "\x1b[34m###### Testing: ${test} --${mode} --${o1} --${o2} ######\x1b[0m"
             outputFile="text-block-tests/${test}-${mode}-${o1}-${o2}.out"
             goodFile="text-block-tests/${test}-${mode}-${o1}-${o2}.good"
+            if [ "${mode}" == "replace" ] || [ "${mode}" == "insert" ]  ; then
+               mode2="${mode} ${insertFile}"
+            else
+               mode2="${mode}"
+            fi
             if [ "${test}" == "simple" ] ; then
-               ${RUN} ./text-block -i text-block-tests/simple.txt -o "${outputFile}" -b '<BEGIN-BLOCK>' -e '<END-BLOCK>' --${mode} --${o1} --${o2}
+               ${RUN} ./text-block -i text-block-tests/simple.txt -o "${outputFile}" -b '<BEGIN-BLOCK>' -e '<END-BLOCK>' --${mode2} --${o1} --${o2}
             elif [ "${test}" == "advanced1" ] ; then
-               ${RUN} ./text-block -i text-block-tests/advanced.txt -o "${outputFile}" -b '<BEGIN-BLOCK>' -e '<END-BLOCK>' --${mode} --${o1} --${o2}
+               ${RUN} ./text-block -i text-block-tests/advanced.txt -o "${outputFile}" -b '<BEGIN-BLOCK>' -e '<END-BLOCK>' --${mode2} --${o1} --${o2}
                cat "${outputFile}"
             elif [ "${test}" == "advanced2" ] ; then
-               ${RUN} ./text-block -i text-block-tests/advanced.txt -o "${outputFile}" -b '<MARKER>' --${mode} --${o1} --${o2}
+               ${RUN} ./text-block -i text-block-tests/advanced.txt -o "${outputFile}" -b '<MARKER>' --${mode2} --${o1} --${o2}
                cat "${outputFile}"
             else
                false
@@ -31,14 +37,16 @@ for mode in cat extract remove ; do
             if [ -e "${goodFile}" ] ; then
                if ! diff --color "${outputFile}" "${goodFile}" ; then
                   (
-                     print-utf8 -n -s "\e[1;31;5m█" "▀" "█\e[0m" ;
-                     echo "TEST FAILED!" | figlet -w 64 | print-utf8 -n -C "\e[1;31;5m█\e[25m" "\e[5m█\e[0m" ;
-                     print-utf8 -n -s "\e[1;31;5m█" "▄" "█\e[0m"
+                     ./print-utf8 -n -s "\e[1;31;5m█" "▀" "█\e[0m" ;
+                     echo "TEST FAILED!" | figlet -w 64 | ./print-utf8 -n -C "\e[1;31;5m█\e[25m" "\e[5m█\e[0m" ;
+                     ./print-utf8 -n -s "\e[1;31;5m█" "▄" "█\e[0m"
                   ) >&2
-                  exit 1
+#                   exit 1
                else
                   echo "OK!"
                fi
+            else
+               echo "No good file for $(basename "${outputFile}")!"
             fi
          done
       done
