Further clean-ups.

diff --git a/src/try-hard b/src/try-hard
--- a/src/try-hard
+++ b/src/try-hard
@@ -50,17 +50,17 @@ while [ $# -gt 0 ] ; do
    elif  [ "${arg}" == "--" ] ; then
       break
    else
-      eval_gettext >&2 "ERROR: Invalid argument ${arg}!"
+      echo >&2 "$(eval_gettext "ERROR: Invalid argument \${arg}!")"
       exit 1
    fi
 done
 
 if [[ ! "${MAX_TRIALS}" =~ ^[0-9]*$ ]] || [ "${MAX_TRIALS}" -lt 1 ] ; then
-   eval_gettext >&2 "ERROR: Invalid maximum trials ${MAX_TRIALS}!"
+   echo >&2 "$(eval_gettext "ERROR: Invalid maximum trials \${MAX_TRIALS}!")"
    exit 1
 fi
 if [[ ! "${DELAY}" =~ ^[0-9]+$ ]] ; then
-   eval_gettext >&2 "ERROR: Invalid delay ${DELAY}!"
+   echo >&2 "$(eval_gettext "ERROR: Invalid delay \${DELAY}!")"
    exit 1
 fi
 
@@ -70,7 +70,7 @@ trial=0
 while true ; do
    trial=$(( trial+1 ))
    if [ "${VERBOSE}" -eq 1 ] ; then
-      echo -e "\x1b[34m$(eval_gettext "Trial ${trial}/${MAX_TRIALS}: $*")\x1b[0m"
+      echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Trial \${trial}/\${MAX_TRIALS}: \x1b[37m$*")\x1b[0m"
    fi
 
    # shellcheck disable=SC2068
@@ -78,12 +78,12 @@ while true ; do
 
    if [ ${trial} -ge "${MAX_TRIALS}" ] ; then
       if [ "${VERBOSE}" -eq 1 ] ; then
-         echo -e "\x1b[34m$(eval_gettext "Tried ${MAX_TRIALS} times -> giving up!")\x1b[0m"
+         echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Tried \${MAX_TRIALS} times -> giving up now!")\x1b[0m"
       fi
       exit 1
    fi
    if [ "${VERBOSE}" -eq 1 ] ; then
-      echo -e "\x1b[34m$(eval_gettext "Waiting ${DELAY} s before next try ...")\x1b[0m"
+      echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Waiting \${DELAY} s before next try ...")\x1b[0m"
    fi
    sleep "${DELAY}"
 done
