Improved options handling.

diff --git a/src/Reset-Machine-ID/Reset-Machine-ID b/src/Reset-Machine-ID/Reset-Machine-ID
--- a/src/Reset-Machine-ID/Reset-Machine-ID
+++ b/src/Reset-Machine-ID/Reset-Machine-ID
@@ -175,7 +175,7 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -H | --hostname)
          hostname="$2"
-         shift 2
+         shift
          if [[ ! "${hostname}" =~ ^([a-zA-Z][a-zA-Z0-9-]+\.)*[a-zA-Z][a-zA-Z0-9-]*$ ]] ; then
             # shellcheck disable=SC2005
             echo >&2 "$(eval_gettext "ERROR: Invalid hostname \${hostname}!")"
@@ -186,42 +186,40 @@ while [ $# -gt 0 ] ; do
          ;;
       -M | --skip-machine-id)
          SKIP_MACHINE_ID=1
-         shift
          ;;
       -S | --skip-ssh-configuration)
          SKIP_SSH_CONFIGURATION=1
-         shift
          ;;
       -K | --skip-key-replacement)
          SKIP_SSH_KEY_REPLACEMENT=1
-         shift
          ;;
       -Z | --zabbix)
          ZABBIX_SERVER="$2"
-         shift 2
          ;;
       -A | --install-zabbix-agent)
          INSTALL_ZABBIX_AGENT=1
-         shift
          ;;
       --yes-to-all-i-am-really-sure)
          YES_TO_ALL=1
          applyChanges="yes"
-         shift
          ;;
       -h | --help)
          usage 0
-         # shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 if [ $# -ne 0 ] ; then
    usage 1
diff --git a/src/System-Info/System-Info b/src/System-Info/System-Info
--- a/src/System-Info/System-Info
+++ b/src/System-Info/System-Info
@@ -420,21 +420,25 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -S | --scripts)
          scriptDirectories="$2"
-         shift 2
+         shift
          ;;
       -h | --help)
          usage 0
-         # shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 if [ $# -ne 0 ] ; then
    usage 1
diff --git a/src/X509/extract-pem b/src/X509/extract-pem
--- a/src/X509/extract-pem
+++ b/src/X509/extract-pem
@@ -74,37 +74,37 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -o | --output-prefix)
          OUTPUT_PREFIX="$2"
-         shift 2
+         shift
          ;;
       -1 | --only-first-entry)
          ONLY_FIRST_ENTRY=1
-         shift
          ;;
       -f | --skip-first-entry)
          SKIP_FIRST_ENTRY=1
-         shift
          ;;
       -l | --skip-last-entry)
          SKIP_LAST_ENTRY=1
-         shift
          ;;
       -q | --quiet)
          QUIET=1
-         shift
          ;;
       -h | --help)
          usage 0
-         # shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 if [ $# -lt 1 ] ; then
    usage 1
diff --git a/src/X509/test-tls-connection b/src/X509/test-tls-connection
--- a/src/X509/test-tls-connection
+++ b/src/X509/test-tls-connection
@@ -73,29 +73,31 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -s | --save-certificate)
          CERTIFICATE_FILE="$2"
-         shift 2
+         shift
          ;;
       -n | --no-view-certificate)
          VIEW_CERTIFICATE=0
-         shift
          ;;
       -c | --no-check-certificate)
          CHECK_CERTIFICATE=0
-         shift
          ;;
       -h | --help)
          usage 0
-         # shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 if [ $# -lt 2 ] ; then
    usage 1
diff --git a/src/X509/view-crl b/src/X509/view-crl
--- a/src/X509/view-crl
+++ b/src/X509/view-crl
@@ -87,17 +87,21 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -h | --help)
          usage 0
-         # shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled argument $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 if [ $# -lt 1 ] ; then
    usage 1
